### ISSUE TITLE
LspCodeLens support

### ISSUE THREAD

**Issue by guibou** [EdenEast/nightfox.nvim#10]
`LspCodeLens` is the color of virtual text added by Lsp when code lens are used.

**Comment by guibou** [comment]
Thank you.

I'm trying to override this entry, however I was used to do `hi link LspCodeLens Foo`, but it does not work.

I also tried:

```lua
vim.g.nightfox_colors = {LspCodeLens = {fg = require('nightfox.colors').orange }}
```

But when I'm doing `colorscheme nightfox`, it complains that the `LspCodeLens` color does not exists.

**Comment by EdenEast** [comment]
The variable `nightfox_colors` is a way to override any defined color. So for example if you wanted to change the red of a theme you can do so (see [issue 3](https://github.com/EdenEast/nightfox.nvim/issues/3#issuecomment-901218859) for an example)

Currently nightfox does not have a mechanism for overriding a highlight group. You can however override a highlight group yourself. Here is a code example of me overriding the `String` highlight group.

```lua
-- Setting the style you want the require colors to return
vim.g.nightfox_style = "nordfox"

-- Set the colorscheme
vim.cmd([[colorscheme nightfox]])

-- Get the colors from nightfox and util functions
local colors = require("nightfox.colors").setup()
local util = require("nightfox.util")

-- Pass highlight group you want to override with values
-- Values can be: bg, fg, style, and sp
util.highlight("String", { fg = colors.orange })

```
