### ISSUE TITLE
Idea: Register your own palette

### ISSUE THREAD

**Issue by EdenEast** [EdenEast/nightfox.nvim#105]
**Is your feature request related to a problem? Please describe.**
Nightfox has become modular enough and big enough that it could be described as a colorscheme framework. The only requirement to create your own theme with nightfox is define your own `palette`.

**Describe the solution you'd like**
Nightfox has an api to register a new pallet, The palette can also define a spec as well in case someone wants to change the mapping from `palette` to `spec`.

**Comment by JoseConseco** [comment]
Imo it would be also cool, if  nightfox.color module, could be put into separate plugin/repo. It is helpful for adjusting colors more plug devs could use it, if it was separate plug. 
I myself wanted to make plug, based on it - which would create new highlights based on existing one but with adjusted color.  For example :    create 'Indent_blankline' highlight,  based on 'Normal', but 10% darker.   
`hl_adjust.highlight_adjust_col("IndentEven", "Normal", {action='contrast', factor=-6}) -- reduce contrast by  -6`
This placed into autogroup callback: "ColorScheme" event  - would automatically match `IndentEven` hi to new theme 'Normal' highlight. 
This solves the issue were some manually set highlights only match one theme. And if you change theme, your color look like shit. 
What do you think?

**Comment by jgollenz** [comment]
@EdenEast I take away from this that you do not plan to accept any future themes for Nightfox? I've seen Nordfox and Terafox and started working on a Gruvbox port ... [Gruvfox.](https://github.com/jgollenz/nightfox.nvim/tree/feature/gruvfox). It's a work in progress, but I'm wondering if it's also a work in vain.

**Comment by EdenEast** [comment]
@JoseConseco That is an interesting idea. I think that might be better in a dedicated plugin.

**Comment by EdenEast** [comment]
@jgollenz I am unsure about adding new themes (popular global themes like gruvbox, one dark, dracula, etc...) to nightfox.

When I originally wrote nightfox I created the `nightfox` style first. I saw this [reference][nordfox] and used that to
create `nordfox` as the second style. I added `nordfox` as I wanted to use the same colors for the different elements of
neovim but change the actual colors used.

Now that nightfox is (some what) popular and other people are using it I am not sure I should have added themes like `nordfox`.
I have not removed it as a lot of people use it, but I would like to add themes that are original and unique to nightfox
like `terafox`. I was inspired to create `terafox` after seeing it's [reference][terafox] image. There are also not a
lot of themes that are focused around dark green.

With that being said, nightfox has become mature, modular, and customizable enough that I would loosely describe it as a
colorscheme framework. The only thing that needs to be defined is a `palette`.

I am not apposed to adding well known colorschemes to nightfox. I would however like to find some way to opt into them.
The color `palette` can be defined in lua but the `colors/****fox.lua` file would not be present. You then can say in
some mechanize to say that you would also want a `colors/nordfox.vim` as an example.

If I get inspired by another image and want to create a new colorscheme I will be adding it to nightfox as I dont want
to maintain multiple colorschemes plugins. It is much easier to just add it to nightfox.

Not sure I answered your question or just did a brain dump. 😅 

[nordfox]: https://i.imgur.com/LzJYkpS.jpeg
[terafox]: https://torako.wakarimasen.moe/file/torako/wg/image/1622/83/1622838138777.jpg

**Comment by jgollenz** [comment]
Hm, It's complicated since this repo is now somewhere in between a colorscheme and a colorscheme framework. My question is: why did you choose to do it this way in the first place? You could have used ColorBuddy or a different colorscheme framework that already exists and build nightfox on top of that. The fact that you did not do that and instead created your own suggests, that you were not quite satisfied with the available frameworks in existence. Consider this: is the underlying logic on which nightfox and the other variants build upon generic enough so that people generally would benefit if they could use it as a platform for their own colorschemes? Perhaps it could work a bit like other neovim package managers do, just for colorschemes? E.g. 

```
use{"EdenEast/nightfox.nvim", 
        colorschemes = { 
            "jgollenz/gruvfox.nvim", -- shameless plug, sorry
            "vampirePerson/bloodfox.nvim",
            "vulpeslover/darkfox.nvim"
        }
```

You could even go so far to completely separate nightfox from the framework and establish nightfox like [rose pine](https://github.com/rose-pine/rose-pine-theme) or [nord](https://github.com/arcticicestudio/nord), where their respective repos don't really bother about anything else than specifying the colorscheme itself. It would definitely help spreading the theme to other editors / tools. But it's a lot of work as well, obviously.

PS: Funny, I did not for a second think that Terafox could be based on anything other than solarized dark. Now that I compare them side by side, they are quite different. Well done :)

**Comment by EdenEast** [comment]
When I first wrote nightfox I used [Tokionight ](https://github.com/folke/tokyonight.nvim) as a base. It grew and expanded from there. I did a major rewrite in #77 which added the concept of `palettes` to define the colors of a style and `specs` to define how a palette is mapped to highlight groups.
The goal of nightfox was to create colorscheme that was highly customizable as I feel that a colorscheme is very subjective. What I think looks good might not be for someone else. Even I customize nightfox and dont use the default (I currently set operators to `orange`).

This has made me think of creating a colorscheme framework like colorbuddy, and factor out nightfox and terafox into a their own colorschemes. This however becomes much harder to maintain.

I would like to also try and keep the `fox` theme that I have going on here. Not sure what it would be called. I am warming up to the idea of breaking it up and creating some sort of org like rose-pine and catppuccin.

**Comment by jgollenz** [comment]
I strongly agree on the fox theme, it's one of the things that got me interested in the plugin in the first place (after I've seen the variants and their respective names). Personally I'd go with one of the names for [a group of foxes](https://en.wikipedia.org/wiki/Fox), skulk or leash.

One thing I was wondering is how the glue between a colorscheme framework and an actual colorscheme would look like? If it's just different repos that conform to some sort of specification, you can't really force people to stick with the fox theme. If it's enabled by you on a per colorscheme basis you surely can (to some degree). Depends on how strict you want to be.

**Comment by luxus** [comment]
is there still interest to make this happens? i would love to add a rosepine fox or a kanagawa fox :D

**Comment by EdenEast** [comment]
This is still something that I would consider. Also with the refactor of how nightfox is configured this can be done easier. This how ever is not my current priority as I am currently down the rabbit hole of reading cvd (color vision deficiency) papers and researching colorblindness for #89.

**Comment by EdenEast** [comment]
Closing this issue. If this was to be implemented it would be a separate plugin framework.
