### ISSUE TITLE
`vim.cmd` in Neovim is `vim.command` in Vim

### ISSUE THREAD

**Issue by djpohly** [EdenEast/nightfox.nvim#108]
## Description

Loading the colorscheme in Vim (after addressing #107) results in the error "attempt to call a nil value (field 'cmd')" from precompiled Lua file.  Status of known Lua incompatibilities in Neovim are being tracked at neovim/neovim#12537, in case it helps.  I don't know whether changing the `vim` table would have undesirable side effects, but it's possible that a well-placed

```lua
if vim.fn.has("nvim") == 0 then
  vim.cmd = vim.command
end
```

could be a quick fix; otherwise a separate

```lua
function vimcmd(cmd)
  if vim.fn.has("nvim") == 0 then
    vim.command(cmd)
  else
    vim.cmd(cmd)
  end
end
```

could be used.

## Behavior

**Expected behavior**
Beautiful colors, of course.

## Configuration

None/default.

**Reproduce**

1. `vim`
2. `:colo nightfox`

**Comment by EdenEast** [comment]
Thanks for catching this. I dont use vim and had a hard time finding out how to get it built with lua. Finally found a way to add it to my nix flake. Should make it easier for me to check if changes break vim.
