### ISSUE TITLE
Highlight and warning background colors off

### ISSUE THREAD

**Issue by Gako358** [EdenEast/nightfox.nvim#113]
**Describe the solution you'd like**
I might have missed this but trying to find a way to turn off the background colors on warnings and errors, or this is not a feature yet?

**Comment by EdenEast** [comment]
When you are referring to warning background colors are you referring to the virtual text from `vim.diagnostic`. If so then yes there is a way to not set the background. Nightfox's modules allow for more specific options for different areas/plugins. For the diagnostic module there is an option defined to toggle the background color.

```lua
require("nightfox").setup({
  options = {
    modules = {
      diagnostic = {
        background = false,
      },
    },
  },
})
```

See [usage](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#modulesdiagnostic) for more details.

**Comment by Gako358** [comment]
Thank you, that was what I was looking for.
