### ISSUE TITLE
Linking syntax highlights.

### ISSUE THREAD

**Issue by JoseConseco** [EdenEast/nightfox.nvim#115]
**Is your feature request related to a problem? Please describe.**
I would like to have exactly same style and color for syntax.conditional and keywords.  We can use palettes to match color, but styles table has no `conditionals` entry. 

**Describe the solution you'd like**
One way to go would to match  `styles` to `syntax` config table, so that we can set styles for all syntax elements. Thus styles table would contain same keys as syntax: 
![image](https://user-images.githubusercontent.com/13521338/161592975-2d817ea8-9976-4c70-b1ba-45099559e7ed.png)
Maybe some keys could be renamed : eg. func  to functions etc. Some removed? 

**Describe alternatives you've considered**
I could try to link `syntax.conditional` to `syntax.keywords`, but I'm not sure which  nvim highlights are affected by those. 
Maybe additional config option: 
```
link_syntax = {
  conditional = {'keywords', 'const' etc}  -- keywords and constants would use same color and style as  conditional.
}
```
could be additional way to solve the issue. It would link `keywords` and `const`  to `conditional` highlight (color and style) in automated way

**Comment by EdenEast** [comment]
Nightfox has the concept of `specs`. Specs are an abstraction layer for mapping the base color palette's of a style to logical groups that can be used to define highlight groups. All styles define a base spec mapping but with most things in nightfox they can be customized. If you would like to make conditionals the same color as keywords this can be done like:

```lua
  local styles = { "nightfox", "dayfox", "dawnfox", "duskfox", "nordfox", "terafox" }
  local specs = {}
  for _, style in ipairs(styles) do
    specs[style] = {
      syntax = {
        conditional = "magenta",
      },
    }
  end
  require("nightfox").setup({ specs = specs })
```

One thing I could see adding if you wanted to set something for every style there could be an `all` style which would apply to all of them. This would save from having the loop.

If you want to find out what highlight group is being applied you can use the [treesitter playground](https://github.com/nvim-treesitter/playground#show-treesitter-and-syntax-highlight-groups-under-the-cursor) command `:TSHighlightCapturesUnderCursor `.
If you dont want to use that for what ever reason and you want a vimscript way of doing it you can check out this section of the [old readme](https://github.com/EdenEast/nightfox.nvim/tree/v1.0.0#vim-highlighting) for a pure vimscript way.

**Comment by JoseConseco** [comment]
Specs are  ok, but AFAIK I wont be able to select style  (eg "BOLD")  for individual spec.syntax.element right?  I already matched specs.syntax color, but for me issue is I cant match style (make it bold), see green words: 
![image](https://user-images.githubusercontent.com/13521338/161626933-61bdaa16-6700-4c96-864f-58f4b53f665f.png)
I matched `syntax.operator`, and `syntax.conditional` to `syntax.builtin0`. 
But there is no way to assign  'bold' font style to  `conditional` or `operator` right? 
That is why I proposed expanding font `styles` table with more items (IMO it should have same keys as  spec.syntax, so we can define font style for each syntax element) 

Now I can see there is group option in nightfox params, which is kind of what I'm looking for - It allows to link the vim highlights. 
But rather than searching for dozen of vim highlights that are defined by `syntax.conditional`, and linking it to 'builtin0', I would like to link groups of highlights for example:
 - link  `syntax.operator` (e.g. color and  style[bold]),  to `syntax.builtin0` 
 This way bunch of highlights that are determined by `syntax.operator`  would be automatically linked to 'syntax.builtin0` by nightfox (including font style - bold,italic etc.). Here is image showing what I mean:
![image](https://user-images.githubusercontent.com/13521338/161631099-8b01e03e-8167-469f-afd7-a9cb73378c98.png).

Another way about it would be to allow user to define which vim highlights are affected by  specs. Then I could remove these highlights from   `operator` and `conditional` and put it into `builtin` category. 
I hope I explained my issue better this time.

**Comment by JoseConseco** [comment]
Ok, I can see you have something called syntax.lua wich seems to do what I want, but it is exposed for config. It has the things I was mentioning above: 
![image](https://user-images.githubusercontent.com/13521338/161634661-ba97a480-8159-4169-8e97-d0c48429e9a2.png)
You can link bunch of high level syntax  elements, rather than deal with  dozens of individual vim highlights. 
The items in syntax.lua are also named more user friendly, compared to spec.syntax   ( func, builtin0,1,2, ident,   vs  Function, Identifier, Label etc)

**Comment by EdenEast** [comment]
> But there is no way to assign 'bold' font style to conditional or operator right?

There is a way to set the style for different syntax groups. This is in [options.styles][style-opts].
(Looking at the usage doc I see I am missing this list of syntax types.). The current list of syntax types are:

- comments
- functions
- keywords
- numbers
- strings
- types
- variables

I can see ppl might want more then just these listed. `options` was used for this as it is easy for someone to
understand how to set some options and dont have to figure out things like `specs` and `palettes` if all they want to
configure is making their comments italics.

> Another way about it would be to allow user to define which vim highlights are affected by specs. Then I could remove these highlights from operator and conditional and put it into builtin category.

This is something similar to the `groups` table that you found.

> Ok, I can see you have something called syntax.lua wich seems to do what I want, but it is not exposed for config?

The `syntax.lua` file defines the default highlight groups for vim. This list is also found in the help `:help
group-name`.  If you are using `treesitter` to highlight that file is called [treesitter.lua]. This list is also found
in the help `:help nvim-treesitter-highlights`.

> I matched syntax.operator, and syntax.conditional to syntax.builtin0.  But there is no way to assign 'bold' font style to conditional or operator right?

An example of this would be:

```lua
require("nightfox").setup({
  groups = {
    Conditional = { fg = "syntax.builtin0", style = "bold" },
    Operator = { fg = "syntax.builtin0", style = "bold" },
  },
})
```

**Comment by JoseConseco** [comment]
Thx, groups solved the issue. And in support link='xyz' too which is great. Here is my dayfox after tweaking:
![image](https://user-images.githubusercontent.com/13521338/161714166-e1a58282-071f-42a5-8333-74c8eba2e430.png)

Before:
![image](https://user-images.githubusercontent.com/13521338/161715118-727d568f-d62d-498a-8a2c-8b4818fd547e.png)
When sun was shining on my monitor, it was hard to see Hue differences between func name, if conditions,  [and, or]  and 'normal' variables - all these were blending bit much into gray dark font.  Thanks for you patience, and great plugin.  Those are the best themes for NVIM imo.  Closing this.
