### ISSUE TITLE
Duskfox color contrast issues

### ISSUE THREAD

**Issue by sultanahamer** [EdenEast/nightfox.nvim#120]
## Description

The folded text is quite dull and not easy to view

**Note:** If you are not seeing your changes make sure that you clean your compiled files. See status of compiled files
with `:NightfoxStatus` and clean the compiled files with `:NightfoxClean`.

## Behavior
![image](https://user-images.githubusercontent.com/11389059/161939523-9a898cbe-991f-4da3-9046-9180880fcadd.png)

**Expected behavior**
Should be easier to view with better contrast color, below is screenshot from nightfox colorscheme - here these are a bit easier to view

![image](https://user-images.githubusercontent.com/11389059/161941253-b352fa06-cb76-47c7-a21f-6e5a8f8017c6.png)

**Screenshots**

## Configuration

Relevant nightfox's configuration...
All default configuration nothing extra

**Reproduce**

1. open a file with folded text

The only reason I am using duskfox instead of nightfox is because comments text in the nightfox are hard to view similar to this. May be they are using similar color(duskfox folded text color == nightfox commented text color may be)

**Comment by sultanahamer** [comment]
@EdenEast I have started using this color scheme 3 days ago after seeing your post about Terafox in neovim reddit. I started with nightfox and found that comments color is quite dull and not visible so switched to duskfox.

Do let me know what you think about these kind of issues being raised on github. If these are appropriate, I can keep posting these things as I face everyday.

I would be using neovim at least 5 to 8 hours a day with duskfox

At times my comments might seem lame as I am red-green color blind. I presume, I should be seeing blue alright not sure though.

**Comment by EdenEast** [comment]
Thanks for your issue. Looking at the screenshots I do agree that the contrast is a bit to low. I have created a pr to address this (found that I was using the wrong bg shade for folds).

As for colorblindness I would like to have some mechanism for helping with this. I have an open issue regarding this #89. I am just not sure the best way to support this.
