### ISSUE TITLE
Consider `cursor none` for kitty themes

### ISSUE THREAD

**Issue by wimstefan** [EdenEast/nightfox.nvim#124]
First of all I want to thank you for your wonderful work! I'm using it for really everything on all of my computers and am really happy with the looks and customizability of this great theme :D

**Is your feature request related to a problem? Please describe.**
Not really a problem but more a preference I have :)

**Describe the solution you'd like**
Using `cursor none` for all kitty themes or at least leave the cursor configuration up to the user by omitting the configuration option in the template so that the user can set a cursor of own preference in `kitty.conf`.

**Additional context**
To cite the [kitty manual](https://sw.kovidgoyal.net/kitty/conf/?highlight=cursor#opt-kitty.cursor) in this:
> If set to the special value none the cursor will be rendered with a “reverse video” effect. It’s color will be the color of the text in the cell it is over and the text will be rendered with the background color of the cell. Note that if the program running in the terminal sets a cursor color, this takes precedence. Also, the cursor colors are modified if the cell background and foreground colors have very low contrast.

**Comment by EdenEast** [comment]
The extra generation are static and don't have any logic for the output generation. For this the kitty template could be added so that you can uncomment the `cursor none` line if someone wants that instead of the default.

**Comment by wimstefan** [comment]
Thanks a lot for coming back to my issue!
I had added the `cursor none` option already to the kitty template and created the theme files with `make extragen`.
I'll keep doing that after you've explained how the generation logic works :)
kitty was complaining by the way about the trailing comment - I've created a little patch to fix that:
```patch
  diff --git a/lua/nightfox/extra/kitty.lua b/lua/nightfox/extra/kitty.lua
  index 9b246cf..4642dd8 100644
  --- a/lua/nightfox/extra/kitty.lua
  +++ b/lua/nightfox/extra/kitty.lua
  @@ -16,7 +16,8 @@ url_color ${palette.green}

   # Cursor
   cursor ${fg1}
  -# cursor none # uncomment for reverse background
  +# uncomment for reverse background
  +# cursor none

   # Border
   active_border_color ${palette.blue}
```

**Comment by EdenEast** [comment]
Thanks for letting me know that kitty does not like trailing comments I have updated the template in commit [1fa9739](https://github.com/EdenEast/nightfox.nvim/commit/1fa9739a2ee45f5a0048e18bac43f90d1edb77ed)
