### ISSUE TITLE
Does not play well with hop.nvim

### ISSUE THREAD

**Issue by zbouslikhin** [EdenEast/nightfox.nvim#125]
## Description

I'm using hop.nvim to quickly navigate across my file. For that, I'm modifying the color of the highlighted keys to the same color as it is more comfortable for me.
However, nightfox overrides my custom hop highlights.
I tried running an autocmd whenever colorscheme is changed, but does not work at first run (when it is set through nightfox_config.lua, but only by manually running the command.
As a reference, [this bug report from hop's github repo might be helpful ](https://github.com/phaazon/hop.nvim/issues/169#issuecomment-971759419)

## Behavior

**Expected behavior**
Do not override 

**Screenshots**

## Configuration

**Reproduce**

```
# hop.lua
local hop = require("hop")

hop.setup({})

vim.api.nvim_exec([[
    augroup MyColors
    autocmd!
    autocmd ColorScheme * hi HopNextKey guifg=#ff9900
                      \ | hi HopNextKey1 guifg=#ff9900
                      \ | hi HopNextKey2 guifg=#ff9900
    augroup END
]], true)
```

```
# nightfox_config.lua
vim.cmd("colorscheme duskfox")
```

## Additional info / context

NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

**Comment by EdenEast** [comment]
There are a couple of point to help you with your issues. Nightfox does provide a couple of ways to help with this. 

`groups` can be used to override the value that nightfox will set.

```lua
require('nightfox').setup({
  groups = {
    HopNextKey = { fg = "#ff9900" },
    HopNextKey1 = { link = "HopNextKey" },
    HopNextKey2 = { link = "HopNextKey" },
  }
})
```

`modules` can be used to disable the hop module so that nightfox does not define it's own.

```lua
require('nightfox').setup({
  options = {
    modules = {
      hop = false
    }
  }
})
```

As for `autocmds`, the builtin command `colorscheme` is responsible to triggering the autocmd event `ColorScheme`.

**Comment by zbouslikhin** [comment]
All solutions worked well. I went using the second solution, which disables hop module in order to keep the two plugins configuration separated. Thank you!

The idea behind using autocmds was because I assumed that since colorscheme is ran whenever nvim is started, an auto command would be triggered too, but this was not the case on first run.
