### ISSUE TITLE
Incorrect bufferline.nvim theming

### ISSUE THREAD

**Issue by gegoune** [EdenEast/nightfox.nvim#139]
## Description

Recently added [bufferline.nvim support](https://github.com/EdenEast/nightfox.nvim/pull/114/files#diff-f778d23e0cdde91d178a9c83df5e83cb72dd3846be136b9e7eb2825bd9fdd652R27-R28) has some issues.

## Behavior

**Expected behavior**
One should see:
* tab numbers on the very right hand side of the tabbar — at the moment:
  * inactive tab number is not visible at all ([fg == gb](https://github.com/EdenEast/nightfox.nvim/pull/114/files#diff-f778d23e0cdde91d178a9c83df5e83cb72dd3846be136b9e7eb2825bd9fdd652R15))
  * active tabpage is not easy to see ([low contrast](https://github.com/EdenEast/nightfox.nvim/pull/114/files#diff-f778d23e0cdde91d178a9c83df5e83cb72dd3846be136b9e7eb2825bd9fdd652R14))
* text for diagnostics for inactive window are not readable ([fg == bg](https://github.com/EdenEast/nightfox.nvim/pull/114/files#diff-f778d23e0cdde91d178a9c83df5e83cb72dd3846be136b9e7eb2825bd9fdd652R27-R28))
* directory part of path has different background than the filename and rest of the 'tab' (see `_nightfox/_nightfox_compiled…` one screenshot)

**Screenshots**

<img width="864" alt="Screenshot 2022-04-20 at 10 35 27" src="https://user-images.githubusercontent.com/69750637/164175470-d30d113c-8337-47b6-b9aa-e533a4b7ca77.png">

## Configuration

No configuration on nightfox part.

**Reproduce**

1. open nvim and some buffers
2. `:tabnew`
3. cause any diagnostics to show errors (didn't check for warnings. hints or info level of diagnostics)
4. observe issues as on screenshot

<details>
<summary>minimal_init.lua</summary>

```lua
-- `minimal_init.lua` used for reproducible configuration
-- Open with `nvim --clean -u minimal_init.lua`

local is_windows = vim.fn.has("win32") == 1
local function join(...)
  local sep = is_windows and "\\" or "/"
  return table.concat({ ... }, sep)
end

local root_tmp = is_windows and os.getenv("TEMP") or "/tmp"
local site_path = join(root_tmp, "nvim", "site")
local pack_path = join(site_path, "pack")
local install_path = join(pack_path, "packer", "start", "packer.nvim")
local compile_path = join(install_path, "plugin", "packer_compiled.lua")
vim.opt.packpath = site_path

local function load_plugins()
  local packer = require("packer")
  local use = packer.use
  packer.reset()
  packer.init({ compile_path = compile_path, package_root = pack_path })

  use("wbthomason/packer.nvim")
  use("EdenEast/nightfox.nvim")
  use("akinsho/bufferline.nvim")

  packer.install()
end

_G.load_config = function()
  require("bufferline").setup({
    options = {
      diagnostics = "nvim_lsp",
      -- max_name_length = 25,
      -- tab_size = 18,
      -- view = 'multiwindow',
      themable = true,
      numbers = function(opts)
        return opts.id .. '.'
      end,
    },
  })

  require("nightfox").setup({})

  vim.cmd("colorscheme nightfox")
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```
</details>

## Additional info / context

I have tried to reproduce with minimal config issue where directory parts of path are displayed on bufferline but couldn't for some reason. I am not sure what in my configuration is causing it, but at least numbers should appear with incorrect background as well as tabs and diagnostics.

Potentially related explanation from @akinsho https://github.com/akinsho/bufferline.nvim/issues/386#issuecomment-1103849289
Potentially related issue https://github.com/akinsho/bufferline.nvim/issues/391

**Comment by iworkinpixels** [comment]
I came here to report the same bug, looks like someone beat me by an hour! I'm using LunarVim with nightfox.

**Comment by EdenEast** [comment]
I have tried to fix this but bufferline really does not like working with colorschemes and will override the colors. I would have to redefine all of their highlight definitions. The plugin also does not just link to other defined highlight (for example `DiagnosticError`) so there is an order issue you have to set the colorscheme before this plugin is loaded.

I am thinking of removing support for this plugin. The plugin author recommends that ppl customize though its interface. 

I will however fix the issue with `nvim_set_hl` and `Normal` which I was not aware of.

**Comment by gegoune** [comment]
Thank you @EdenEast. I do agree that removing highlights is the way to go in that situation.
