### ISSUE TITLE
Request iterm2 port

### ISSUE THREAD

**Issue by gabrielbidula** [EdenEast/nightfox.nvim#14]
Beautiful theme, good job!

I would like to have it ported to iterm2, if someone knows how to do it...

Cheers

**Comment by EdenEast** [comment]
I created a PR to add Iterm2 to the extra generation. Can you confirm that these  work as I dont have a mac and dont use ITerm. You can find the generated file [here](https://github.com/EdenEast/nightfox.nvim/blob/feat/iterm/extra/nightfox/nightfox_iterm.itermcolors).

**Comment by gabrielbidula** [comment]
@EdenEast Hey, it works, just tested the nordfox version. Thanks
