### ISSUE TITLE
Add cursorColor and selectionBackground for Windows Terminal config

### ISSUE THREAD

**Issue by ChrHorn** [EdenEast/nightfox.nvim#148]
## Description

The fields `cursorColor` and `selectionBackground` are currently not set for the Windows Terminal config. These fields default to `#ffffff`, which makes the cursor/selection invisible when using light themes.

## Behavior

**Expected behavior**
Set `cursorColor` and `selectionBackground` to the appropriate values.

**Screenshots**
![image](https://user-images.githubusercontent.com/17070041/166241301-0bdfcd3f-5388-446a-8e19-fbaece85de77.png)
Dayfox with nearly invisible cursor

**Comment by EdenEast** [comment]
I created a PR to address this let me know if this resolves your issue.
