### ISSUE TITLE
Comments are hard to read when cursorline is enabled

### ISSUE THREAD

**Issue by AlxHnr** [EdenEast/nightfox.nvim#155]
## Description

The contrast between comments and the cursorline is very weak. This problem affects only nightfox, not terafox and duskfox. I've tested this on multiple different monitors, with and without nightshift/redshift.

## Behavior

**Expected behavior**

Nightfox should be just as easy to read as the other fox themes in this repository. Even without the cursorline, the comment contrast is pretty weak and should be increased. When dimming my monitor, the first screenshot below is barely readable, while the others are great.

**Screenshots**

![nightfox](https://user-images.githubusercontent.com/8235638/168157520-a8d052c1-7170-4a31-85c0-16e3a8b4b211.png)
![duskfox](https://user-images.githubusercontent.com/8235638/168157523-5ba290a8-6799-432d-aa77-537cf5f3d830.png)
![terafox](https://user-images.githubusercontent.com/8235638/168157510-87cf36c5-a847-4b64-af95-d83968a50a13.png)
![dayfox](https://user-images.githubusercontent.com/8235638/168157527-0bb62358-8c06-4d08-abb6-bb08331b916b.png)

## Additional info / context

Similar to #120. Maybe related to #89

**Comment by EdenEast** [comment]
I created a PR that brightens nightfox's comment color. Let me know if this is more readable.

**Comment by AlxHnr** [comment]
I've played around with your PR and commented there. But I found another highlighting group where nightfox has a much weaker contrast than the other foxes: Visual selections. Let me find a good value for that.

**Comment by AlxHnr** [comment]
Increasing the hsv brightness of `Visual` by 5 lands us at `#2d3d55`. Comparisons:

# Old nightfox vs new nightfox
![nightfox-old](https://user-images.githubusercontent.com/8235638/168379353-4a01b790-4e14-4c1b-9fc5-863a277ce465.png)
![nightfox-new](https://user-images.githubusercontent.com/8235638/168379354-f207ba40-b113-4cd2-a350-e4003d5ee760.png)

# Old nightfox vs duskfox
![nightfox-old](https://user-images.githubusercontent.com/8235638/168379353-4a01b790-4e14-4c1b-9fc5-863a277ce465.png)
![duskfox](https://user-images.githubusercontent.com/8235638/168379357-5bdcef26-c426-423e-b7c0-b6bfc5ba36f2.png)

# New nightfox vs duskfox
![nightfox-new](https://user-images.githubusercontent.com/8235638/168379354-f207ba40-b113-4cd2-a350-e4003d5ee760.png)
![duskfox](https://user-images.githubusercontent.com/8235638/168379357-5bdcef26-c426-423e-b7c0-b6bfc5ba36f2.png)
