### ISSUE TITLE
Submit to iTerm2-Color-Schemes

### ISSUE THREAD

**Issue by ModProg** [EdenEast/nightfox.nvim#156]
E.g. `wezterm` pulls its colorschemes from this repo https://github.com/mbadolato/iTerm2-Color-Schemes/ so if this was included there it would be built-in.  

I don't know if there might be issues arising due to different assignment of iterm colors and the other terminal themes in the `extra` module, but this would also allow using this colorscheme for all terminals supported by  https://github.com/mbadolato/iTerm2-Color-Schemes/.

**Comment by digitallyserviced** [comment]
Second this!
Love these themes. Love WezTerm, Would love to see it added as a default into WezTerm and the preferred way is through this iterm2 color schemes repo.

If you would like to have someone to liase between the repos I would gladly help!

**Comment by wez** [comment]
@ModProg @digitallyserviced: do either of you want to take a crack at https://github.com/EdenEast/nightfox.nvim/issues/183 as an alternative way to get this into wezterm?

**Comment by EdenEast** [comment]
Closing this as this is resolved by #184
