### ISSUE TITLE
NerdTree background color

### ISSUE THREAD

**Issue by zbouslikhin** [EdenEast/nightfox.nvim#164]
Using duskfox as my colorscheme. However, looking at this screenshot, NERDTree has a different background colour. How can I get that?

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/47977073/170880956-61a72d32-d21e-4ebc-a0e5-3c4715222b09.png)

**Comment by EdenEast** [comment]
The file tree in the screenshot is [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua).

**Comment by zbouslikhin** [comment]
Thanks.

Changing the background colour for things like a file manager, treesitter view etc.. help a lot differentiating what each pane is for.
I was wondering if it makes any sense to have such feature configured for popular plugins such as CHADTree etc?

**Comment by EdenEast** [comment]
Nightfox supports a lot of popular plugins ([list](https://github.com/EdenEast/nightfox.nvim#supported-plugins)). If you want nightfox to support a plugin you can either create a pr that adds, or define it yourself with `groups`.

From quickly glancing it looks like CHADTree does not define any highlight groups but instead takes the highlight group that should be applied though its [config](https://github.com/ms-jpq/chadtree/blob/chad/docs/THEME.md).
