### ISSUE TITLE
Lualine status line colors

### ISSUE THREAD

**Issue by sdemura** [EdenEast/nightfox.nvim#175]
How can I set a different color the different modes? Currently NORMAL and TERMINAL the same color. It would be nice to be able to make TERMINAL a different color, so as to help differentiate modes. Thanks!

**Comment by EdenEast** [comment]
I see that the lualine config did not define a terminal color. This has been updated in pr #176. Let me know if this fixes your issue.

**Comment by sdemura** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/11758459/177534073-b9c757fa-b4c7-4cf3-ac58-41180a52e5b2.png">

Perfect. Thanks @EdenEast !
