### ISSUE TITLE
The current tab is not highlighted for lightline

### ISSUE THREAD

**Issue by jhscheer** [EdenEast/nightfox.nvim#187]
If no theme is selected (or another supported theme), lightline will show the current tab with a different background color.
However, if the theme is set to nightfox, the background color of all open tabs is the same.

```
let g:lightline = {
      \ 'colorscheme': 'nightfox',
      \ }
```

`NVIM v0.7.2`

@4513ECHO Do you have an idea how to fix this?

**Comment by EdenEast** [comment]
It looks like lightline handles both the statusline and the tabline. The field `tabsel` is not currently defined. This can be added.

**Comment by EdenEast** [comment]
This issue is resolved @jhscheer can you kindly confirm.

**Comment by jhscheer** [comment]
I confirm that this issue is resolved.
Thank you very much for the super fast fix!
