### ISSUE TITLE
Add retro tab bar thumbing for wezterm

### ISSUE THREAD

**Issue by gegoune** [EdenEast/nightfox.nvim#191]
https://github.com/catppuccin/wezterm/blob/main/dist/catppuccin-frappe.toml#L38-L81 shows what they're setting; those fields are documented in the context of https://wezfurlong.org/wezterm/config/appearance.html#retro-tab-bar-appearance
The same fields/structure is also accepted in the toml file.

If you wanted to play around with that, it might be most convenient to do something like this (recent nightly build required):

```lua
local wezterm = require 'wezterm'

local colors, metadata = wezterm.color.load_scheme("/path/to/file/from/this/repo.toml")

colors.tab_bar = {
   -- stuff
}

wezterm.color.save_scheme(colors, metadata, "/tmp/output.toml")

return {
  colors = colors,
}
```

that would help you figure out what to use in your toml template for the code gen used here in nightfox.

_Originally posted by @wez in https://github.com/EdenEast/nightfox.nvim/issues/183#issuecomment-1189655306_

@wez described how to start on theming for retro tab bar. I have come up with some colours that work for me, but probably will require some tuning (I hide open-new-tab button).

```lua
colors.tab_bar = {
  background = '#191c23',
  active_tab = {
    bg_color = '#2e3440',
    fg_color = '#d8dee9',
  },
  inactive_tab = {
    bg_color = '#191c23',
    fg_color = '#667084',
  },
  inactive_tab_hover = {
    bg_color = '#d3d6cf',
    fg_color = '#1a1b26',
  },
  new_tab = {
    bg_color = '#191c23',
    fg_color = '#191c23',
  },
  new_tab_hover = {
    bg_color = '#d3d6cf',
    fg_color = '#1a1b26',
  },
}
```

@EdanEast, is it something you would be willing to add to nightfox?

**Comment by EdenEast** [comment]
Hey @gegoune, when this was brought up initially I was going to look into adding this into the extra I just forgot to look into it. This is something that I can add.

**Comment by EdenEast** [comment]
@gegoune I created a pr adding retro tab support.

**Comment by wez** [comment]
nightly wezterm has been sync'd with these changes. Thanks!

**Comment by gegoune** [comment]
Thank you both!
