### ISSUE TITLE
NightfoxCompile doesnt take into consideration spec overrides

### ISSUE THREAD

**Issue by tsakirist** [EdenEast/nightfox.nvim#192]
## Description

`NightfoxCompile` doesn't seem to take into consideration all the configuration options that are set during the `setup` call, most specifically changes to the `specs`.

## Behavior

**Expected behavior**
Compiled file should contain configuration options taking into consideration the `specs` overrides.

## Configuration

```lua
  specs = {
            nordfox = {
                git = {
                    changed = colors.blue.base,
                },
                syntax = {
                    builtin0 = colors.magenta.bright,
                },
            },
        },

```

**Reproduce**

1. Setup plugin according to the configuration in `minimal_init.lua`.
2. Compile nightfox settings with `:NightfoxCompile`
3. Restart neovim
4. Check that `specs` overrides are not applied to the compiled theme

<details>
<summary>minimal_init.lua</summary>

A `minimal_init.lua` file template is located at the root of the project.

```lua
use {
    "EdenEast/nightfox.nvim",
    config = function()
        local colors = require("nightfox.palette").load("nordfox")
        require("nightfox").setup {
            options = {
                compile_path = vim.fn.stdpath "cache" .. "/nightfox",
                compile_file_suffix = "_compiled",
                specs = {
                    nordfox = {
                        git = {
                            changed = colors.blue.base,
                        },
                        syntax = {
                            builtin0 = colors.magenta.bright,
                        },
                    },
                }
            }
        }
        vim.cmd.colorscheme("nordfox")
    end,
}
```

</details>

## Additional info / context

Latest neovim nightly:
`NVIM v0.8.0-dev-768-gb8dcbcc73`

**Comment by EdenEast** [comment]
Looking at your full packer sample code there is an issue with your setup call. You have `specs` under `options`, these should be on the same level. Also you dont need to require nordfox's colors you can use the templates instead. Also `compile_path` and `compile_file_suffix` default to the values you are specifying. Correct setup call:

```lua
use({
  "EdenEast/nightfox.nvim",
  config = function()
    require("nightfox").setup({
      options = {
        -- ...
      },
      specs = {
        nordfox = {
          git = {
            changed = "blue",
          },
          syntax = {
            builtin0 = "magenta.bright",
          },
        },
      },
    })
    vim.cmd.colorscheme("nordfox")
  end,
})
```

**Comment by tsakirist** [comment]
> Looking at your full packer sample code there is an issue with your setup call. You have `specs` under `options`, these should be on the same level. Also you dont need to require nordfox's colors you can use the templates instead. Also `compile_path` and `compile_file_suffix` default to the values you are specifying. Correct setup call:
> 
> ```lua
> use({
>   "EdenEast/nightfox.nvim",
>   config = function()
>     require("nightfox").setup({
>       options = {
>         -- ...
>       },
>       specs = {
>         nordfox = {
>           git = {
>             changed = "blue",
>           },
>           syntax = {
>             builtin0 = "magenta.bright",
>           },
>         },
>       },
>     })
>     vim.cmd.colorscheme("nordfox")
>   end,
> })
> ```

Fixed, the configuration, but still the problem exists, it seems `specs` overrides do not apply to the compiled file.
(I like repeating the default values in the config, so that it's easier to change them on the fly)

I'm attaching a screenshot:

![nordfox_compiled](https://user-images.githubusercontent.com/20475201/183300276-048df8c6-fe52-4c9c-812f-ce258b365ce3.png)

**Comment by nullchilly** [comment]
Try `source | NightfoxCompile`

**Comment by tsakirist** [comment]
> Try `:source | NightfoxCompile`

Still doesn't work.

Compiled nightfox file, doesn't contain the `git = { changed = colors.blue.base }` change, it uses the default highlight color as depicted in the right section of the attached screenshot, (i.e. ebcb8b color instead of the blue)

**Comment by EdenEast** [comment]
Ah I found the issue. It looks like I was using the wrong name to check for `palette` overrides when loading all `specs`. I created a PR to fix this. Can you let me know if this solves your issue?

**Comment by EdenEast** [comment]
Also if you are trying to change the diff color of vimdiff you should look at [DiffChanged](https://github.com/EdenEast/nightfox.nvim/blob/f8d61de/lua/nightfox/group/editor.lua#L18-L21). Lowercase `diff*` relate to the actual `diff` filetype. An example of that would be opening a patch file.

**Comment by tsakirist** [comment]
> Ah I found the issue. It looks like I was using the wrong name to check for `palette` overrides when loading all `specs`. I created a PR to fix this. Can you let me know if this solves your issue?

Thanks for the fix. I checked out the branch and it worked as expected!


> Also if you are trying to change the diff color of vimdiff you should look at [DiffChanged](https://github.com/EdenEast/nightfox.nvim/blob/f8d61de/lua/nightfox/group/editor.lua#L18-L21). Lowercase `diff*` relate to the actual `diff` filetype. An example of that would be opening a patch file.

Thanks for the info.
I need to change  the lowercase diff* highlight, because `GitSignsNr`  are linked to `spec.git`
https://github.com/EdenEast/nightfox.nvim/blob/main/lua/nightfox/group/modules/gitsigns.lua#L11
