### ISSUE TITLE
How to enable terafox

### ISSUE THREAD

**Issue by id-b3** [EdenEast/nightfox.nvim#201]
I'm new to neovim and lua scripting, and finding it very difficult to figure out what I must do to enable the default terafox style. Could someone advise?

**Comment by EdenEast** [comment]
To set `terafox` as a colorscheme all you have to do is execute the command `:colorscheme terafox`. If you want neovim to start with this you would have to add this command to be executed in your configuration (`init.lua` or `init.vim`). Depending on which init file you are using you can add the following:

### lua

```lua
vim.cmd("colorscheme terafox")
```

### vim

```vim
colorscheme terafox
```

Let me know if you have further questions.

**Comment by id-b3** [comment]
Thank you! I tried it before and it failed to work, so I assumed that was a wrong command. I realise now it's because I didn't properly install the plugin before.
