### ISSUE TITLE
Cursor is invisible for dark themes on iTerm

### ISSUE THREAD

**Issue by colepeters** [EdenEast/nightfox.nvim#202]
## Description

Just noticed the cursor has become invisible (or very close to invisible) on the dark themes. It's still fine on the light themes. From the screenshots in the repo, it seems the cursor should be white for these.

## Behavior

**Expected behavior**
The cursor should be visible 😅

**Screenshots**

My cursor is at line 22/col 0 in each of these:

### Nightfox
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1713932/185778116-3335bc83-fe4f-41bd-a568-4bb78e00cef1.png">

### Duskfox
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1713932/185778129-4de77c69-9edb-4dd0-bf62-04cfa47096eb.png">

### Nordfox
<img width="340" alt="image" src="https://user-images.githubusercontent.com/1713932/185778138-13c01eef-0348-401d-9589-e273f2404ae5.png">

### Terafox
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1713932/185778144-b422634d-a105-4cea-936c-30e7c4ad581f.png">

### Carbonfox
<img width="348" alt="image" src="https://user-images.githubusercontent.com/1713932/185778152-97956fe1-4959-4fbd-acd9-7c1ee3956962.png">

### Dayfox
<img width="369" alt="image" src="https://user-images.githubusercontent.com/1713932/185778104-e089aa8e-9762-4ad8-aaf6-6fa5a76f9ebb.png">

### Dawnfox
<img width="365" alt="image" src="https://user-images.githubusercontent.com/1713932/185778110-a11ecaa2-1fd4-4a4e-b5bd-2481c9dcd71f.png">

## Configuration

```lua
require('nightfox').setup({
  options = {
    dim_inactive = true,
    transparent = false,
    modules = {
      cmp = true,
      gitsigns = true,
      lsp_trouble = true,
      native_lsp = true,
      nvimtree = true,
      telescope = true,
      treesitter = true,
    },
  },
  groups = {
    dayfox = {
      ColorColumn = { bg = 'bg0' },
      LineNr = { fg = 'bg4'},
    },
  },
})

vim.cmd('colorscheme dayfox')
```

**Reproduce**

1. Install theme
2. Set to one of the dark themes

## Additional info / context

Absolutely loving these themes — thanks so much for your work on them! 🏆

**Comment by EdenEast** [comment]
Hi @colepeters, the cursor colors are handled by your terminal. Neovim cannot change your cursor (just like how it cant change fonts). This is something that you would have to manage with your terminal. Some terminals like [alacritty] let you use the cells background and foreground color. I dont know about iterm.

[alacritty]: https://github.com/alacritty/alacritty/blob/7d708d5/alacritty.yml#L203-L211

**Comment by colepeters** [comment]
Whoops! Totally right, my bad. Sorry for the noise!
