### ISSUE TITLE
Inlay hint is too showy

### ISSUE THREAD

**Issue by Eliot00** [EdenEast/nightfox.nvim#204]
**Is your feature request related to a problem? Please describe.**

coc.nvim support inlay hint in Vim now, but the virtual text color is too light.

<img width="366" alt="截屏2022-09-01 上午10 54 43" src="https://user-images.githubusercontent.com/18375468/187822162-33c47291-c59d-469b-9e87-21fd1d798997.png">

**Describe the solution you'd like**

Create a gray virtual highlight color. Like JetBrains' IDE

![webstorm](https://resources.jetbrains.com/help/img/idea/2022.2/ws_type_hints_chained_methods.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by EdenEast** [comment]
Added a pr to address this.
