### ISSUE TITLE
Styles option not working as expected

### ISSUE THREAD

**Issue by adrian-soomro** [EdenEast/nightfox.nvim#208]
## Description
I can't seem to get the `styles` option to behave - setting comments to `italic` does nothing.

I've sourced the file, done  `:NightfoxClean` &&  `:NightfoxCompile`, but to no avail. 

I'm quite new to neovim. Is my assumption about the behaviour of this config wrong? Am I missing something or did I make a silly mistake somewhere?

Any help would be greatly appreciated.

## Behavior

Nothing changes, see the attached screenshot.

![image](https://user-images.githubusercontent.com/37105695/189528982-80ae1447-9116-4b73-86d9-94df1a6b3183.png)

**Expected behavior**
I expected any commented text inside the buffer to be displayed with an italic font.

## Configuration

Relevant nightfox's configuration...
```lua
require('nightfox').setup({
  options = {
    styles = {
      comments = "italic",
    }
  }
})

vim.cmd('colorscheme nordfox')

```
**Reproduce**

1. Install nighfox via packer
2. source a luafile containing the above configuration

## Additional info / context

System: Ubuntu 20.04 running on WSL2
nvim -v:
``` 
NVIM v0.8.0-dev-nightly-12-g977790746
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
double-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_H
AS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/
neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az244-86

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
  ```
PackerStatus
![image](https://user-images.githubusercontent.com/37105695/189529355-d214735a-2df1-49bd-ac5b-74cf539907de.png)

**Comment by EdenEast** [comment]
Welcome to neovim! Your nightfox setup is correct. As neovim is a terminal text editor, fonts are handled by your terminal emulator. What terminal emulator are you using?

**Comment by adrian-soomro** [comment]
Thanks for replying so fast ❤️ 

xterm-256color

![image](https://user-images.githubusercontent.com/37105695/189531466-eb8979f1-f523-425a-8825-718edcc742d6.png)

**Comment by adrian-soomro** [comment]
Thanks for helping me out. I tried a different terminal emulator and it works like a charm.

![image](https://user-images.githubusercontent.com/37105695/189531846-5d2ad460-0bf4-4d3a-8e68-9e01b43177a6.png)

**Comment by adrian-soomro** [comment]
For anyone facing similar issue - get [terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-gb&gl=gb) and interact with your WSL2 instance through it, it has support for italics.
