### ISSUE TITLE
Could not use `carbonfox` and `terafox`

### ISSUE THREAD

**Issue by Rawnly** [EdenEast/nightfox.nvim#209]
## Description
I'm not able to use `carbonfox` or `terafox`

## Behavior

**Expected behavior**
I expect to be able to run `:colorscheme carbonfox/terafox`

**Screenshots**
[Screen Rec](https://user-images.githubusercontent.com/16429579/190900151-a42d948c-38a5-4ccd-a6c3-c528fc0e47bb.mp4)

## Configuration
I currently have it installed in my Astronvim configuration. Is installed via `packer` and no extra setup has been done.
![CleanShot 2022-09-18 at 13 40 01](https://user-images.githubusercontent.com/16429579/190900231-5867811f-44d2-41b3-81be-4956a0ae97a1.png)

## Additional info / context
Here is my configuration (`init.lua`) [astronvim-config](https://github.com/Rawnly/astronvim-config/blob/main/init.lua)

**Comment by Rawnly** [comment]
I just noticed that i'm not able to run `:NightfoxStatus` or `:NightfoxClean`, just `:NightfoxLoad`. I think something went wrong during installation. Maybe I'm missing something

**Comment by EdenEast** [comment]
Looking at your packer config you have nightfox set to `v1.0.0`. that is the old version of night fox before a rewrite. If you remove the tag you should have the latest.

**Comment by Rawnly** [comment]
Oh I missed that! Awesome thanks!
