### ISSUE TITLE
How to colorise tildes on empty lines at the bottom so that they appear again?

### ISSUE THREAD

**Issue by eggbean** [EdenEast/nightfox.nvim#211]
On most colour schemes the tildes after EOF are visible, but not with this theme. Is there a way to get them to appear?

I tried `:hi NonText guifg=blue` for example, but nothing seems to have changed.

**Comment by EdenEast** [comment]
The highlight group you are looking for is `EndOfBuffer` you can change this to something else as an example:

```lua
require("nightfox").setup({
  groups = {
    all = {
      EndOfBuffer = { link = "Conceal" },
    }
  }
})
```

**Comment by EdenEast** [comment]
If you dont see any change, make sure to clear nightfox's cache file with `NightfoxClean`. In the example above I am linking the highlight group `EndOfBuffer`  to another highlight group called `Conceal`. You can link it to any other highlight group you want or you could define the fg instead.

```lua
  require("nightfox").setup({
    groups = {
      all = {
        EndOfBuffer = { link = "bg4" },
      },
    },
  })
```

In this example I am setting the foreground color to use the 4th background color defined in the color palette. (see [palette](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#palette) for more information and options)

Let me know if you have any questions.
