### ISSUE TITLE
Ugly colors in vim inside terminal after apply nightfox theme

### ISSUE THREAD

**Issue by Liverm0r** [EdenEast/nightfox.nvim#212]
## Description

When I open nvim inside terminal, spoiled colors are used.
When I open it in neovide, everything is fine.

**Screenshots**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/14236531/194721267-a6e01ef6-0f34-4b09-a411-7b4ad970b725.png">

## Configuration

Default nightfox config.  OSX monterey.

```bash
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

**Reproduce**

Could be reproduced with the [minimal-init.lua](https://github.com/EdenEast/nightfox.nvim/blob/main/minimal_init.lua)

## Additional info / context

If I use any other theme initially (like `everforest`), everything works as expected.

If I switch to `:colorscheme dayfox`, agly colors will be applied, and switching back to `:colorscheme everforest` doesnt fix it.

**Comment by EdenEast** [comment]
What terminal are you using? Does your terminal support true colors? Please see the [requirements](https://github.com/EdenEast/nightfox.nvim#requirements) section.

**Comment by Liverm0r** [comment]
Sorry, missed that one.
