### ISSUE TITLE
Supporting Helix editor

### ISSUE THREAD

**Issue by OpenFoam-User** [EdenEast/nightfox.nvim#213]
**Is your feature request related to a problem? Please describe.**
I have been using the nightfox theme for neovim and I find it very neat.
However, recently, I started playing with the new text editor, Helix (https://github.com/helix-editor/helix), which is inspired by Neovim and Kakoune editors. I wonder if it is possible to make the nightfox theme compatible with it?

**Describe the solution you'd like**
It would be nice to have the nightfox theme work with the helix editor.

Thank you

**Comment by EdenEast** [comment]
This is similar to #68, with asking for vscode. Anyone is welcome to port nightfox and I can link it in the readme.

**Comment by RyonicFire** [comment]
I want to try porting it because as of today I'm also playing around with Helix. @EdenEast should I create a PR where I put the files in the extra directory or should I create a new repo?

**Comment by EdenEast** [comment]
I am not sure how helix does colorschemes/plugins. If using the extra's directory would work then sure you can make a PR. If it would require a new repo, when it is ready you can open a PR and we can add it to the readme.

**Comment by RyonicFire** [comment]
I have created a new [Repo](https://github.com/RyonicFire/nightfox.helix) to avoid cluttering this issue section with helix issues. At the moment only carbonfox is ported because it's my main theme. There are plans to port the others too. PR's are welcome.
