### ISSUE TITLE
Invisible search match on visual highlighted lines

### ISSUE THREAD

**Issue by fedemp** [EdenEast/nightfox.nvim#214]
## Description

Text that is a search match and is inside a visual selection is not visible when cursor is over the match. The foreground and background colors are the same.

## Behavior
**Expected behavior**
Text should be visible, but different from the cursor highlighted text.

**Screenshots**
![Screenshot from 2022-10-10 19-23-39](https://user-images.githubusercontent.com/735314/194961368-af4a1ba3-60f9-4866-8952-218ecf7c3bd4.png)

Note that on line 16, the invisible word is `grep` but since the cursor in column 5, the `g` is visible.

**Reproduce**

1. Create a new buffer.
2. Write the text "Hello world".
3. Search for the `world` text with `/world`.
4. Visually highlight the line with `V`.
5. Move the cursor so it will sit over the `world` word.

**Comment by EdenEast** [comment]
Thanks for the report. Looking at the issue it looks like that visual selection changes the background color but does not change the foreground color. The foreground color is the background color for search. I just have to change this and it should fix the issue.
