### ISSUE TITLE
Lualine: can't see selected buffer in buferline

### ISSUE THREAD

**Issue by Strongleong** [EdenEast/nightfox.nvim#216]
## Description

After updating selected buffer and inactive buffers in lualine have same color

## Behavior

**Expected behavior**
Active and inactive buffers have different distinguishable colors.

**Screenshots**
This is how my buffers looks like:
![image](https://user-images.githubusercontent.com/17177071/196079961-11c89034-f1fb-471a-a69e-aec554b9be19.png)

And this is lualine highlights for buffers (colors are same):
![image](https://user-images.githubusercontent.com/17177071/196080157-6fac26b6-15ac-411c-9713-57a1dd5ecc30.png)
![image](https://user-images.githubusercontent.com/17177071/196080176-e5826bf6-9986-4c1e-a572-76695d0fac5d.png)

## Configuration

Just copy-pasted defaults

```lua
nightfox.setup({
  options = {
    compile_path = cache_dir, 
    compile_file_suffix = "_compiled",
    transparent = false,  
    terminal_colors = true,   
    dim_inactive = false,       
    styles = {   
      comments = "italic",  
      conditionals = "NONE",
      constants = "bold",
      functions = "NONE",
      keywords = "bold",
      numbers = "NONE",
      operators = "NONE",
      strings = "NONE",
      types = "italic,bold",
      variables = "NONE",
    },
    inverse = { 
      match_paren = false,
      visual = false,
      search = false,
    },
    modules = {
      -- ...
    },
  },
  palettes = {},
  specs = {},
  groups = {},
})

```

**Comment by EdenEast** [comment]
Do you have a `minimal_init` file that contains the lualine config that has the issue? I am not able to reproduce this issue with the default lualine setup.

**Comment by Strongleong** [comment]
Sorry, forgot to add minimal config. Here it is:
```lua
-- Bootstrap packer if its not exists
local fn = vim.fn
local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  PACKER_BOOTSTRAP = fn.system({ 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path })
end

local status_ok, packer = pcall(require, 'packer')
if not status_ok then
  vim.notify('Installing Packer')
end

packer.startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'nvim-lualine/lualine.nvim'
  use 'kyazdani42/nvim-web-devicons'
  use "EdenEast/nightfox.nvim"

  if PACKER_BOOTSTRAP then
    require('packer').sync()
  end
end)

local cache_dir = vim.fn.stdpath("cache") .. "/nightfox"

-- Default options
require'nightfox'.setup({
  options = {
    compile_path = cache_dir,          -- Compiled file's destination location
    compile_file_suffix = "_compiled", -- Compiled file suffix
    transparent = false,               -- Disable setting background
    terminal_colors = true,            -- Set terminal colors (vim.g.terminal_color_*) used in `:terminal`
    dim_inactive = false,              -- Non focused panes set to alternative background
    styles = {                         -- Style to be applied to different syntax groups
      comments = "italic",               -- Value is any valid attr-list value `:help attr-list`
      conditionals = "NONE",
      constants = "bold",
      functions = "NONE",
      keywords = "bold",
      numbers = "NONE",
      operators = "NONE",
      strings = "NONE",
      types = "italic,bold",
      variables = "NONE",
    },
    inverse = {             -- Inverse highlight for different types
      match_paren = false,
      visual = false,
      search = false,
    },
    modules = {             -- List of various plugins and additional options
      -- ...
    },
  },
  palettes = {},
  specs = {},
  groups = {},
})

-- setup must be called before loading
vim.cmd("colorscheme nightfox")

require'lualine'.setup({
  sections = {
    lualine_c = {
      {
        "buffers",
        symbols = {
          modified = ' ●',
          alternate_file = '',
          directory = '',
        },
      },

    },
  },
  tabline = {},
})

```

with `nvim -u config.lua` (this minila config) here is result:
![image](https://user-images.githubusercontent.com/17177071/196102848-d105b73c-346a-4d52-a65e-6febbac3da5c.png)

P.S. Sorry for bad English :sweat_smile:

**Comment by Strongleong** [comment]
I think i found the bug. In `lua/nightfox/util/lualine.lua`, line 17. 

You set `c` field, which is setting colors for `c` section of lualine, which is showing buffers in my case. 
`fg` and `bg` colors of `c` is independent from input `color`, means no matter what "category" it is: normal, inactive or any other, color are same. 

Also I think it is my mistake to specify that my problem specifically with buffers line. There is all open buffers, not only currently opened one. Sorry

**Comment by Strongleong** [comment]
@EdenEast sorry for pinging you, but can I ask you about status of this issue?

**Comment by EdenEast** [comment]
I have a pr that should resolve your issue. Please let me know if it does.

**Comment by Strongleong** [comment]
![image](https://user-images.githubusercontent.com/17177071/198179864-35817b6e-9d79-4eea-8cd4-066725bc6e10.png)

Fixed now! Thank you!

**Comment by Strongleong** [comment]
I will close this issue after #228 will be merged to master

**Comment by rlanore** [comment]
This commit break my lualine config. i use all default from nightfox and i can't see inactive buffer into tabline ( bg = fg i think )
My lualine config:
```
require('lualine').setup{
  options = {
    --theme = 'material-nvim'
    --theme = 'tokyonight'
    --theme = 'onedark'
    theme = 'nightfox'
  },
  tabline = {
    lualine_a = { 'buffers' },
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {}
  },
  sections = {
    lualine_a = { 'mode' },
    lualine_b = { 'branch', 'diff'},
    lualine_c = { 
      { "filename", file_status = true, path = 2 },
      { "diagnostics", sources = { "nvim_lsp" } }
    },
    lualine_x = { 'filetype' }
  }
}
```

**Comment by EdenEast** [comment]
@rlanore I created pr #243. This redid the lualine config. Please let me know if it solves your issue.

**Comment by tsakirist** [comment]
#243 has fixed it for me.
