### ISSUE TITLE
Add `noice.nvim` integration

### ISSUE THREAD

**Issue by yutkat** [EdenEast/nightfox.nvim#223]
**Is your feature request related to a problem? Please describe.**
I want support for noice.nvim, which is a hot plugin these days.
https://github.com/folke/noice.nvim

**Describe the solution you'd like**
I would like to add these highlight-groups
https://github.com/folke/noice.nvim#-highlight-groups

**Comment by EdenEast** [comment]
What part of the plugin would you want to override? I tried it out and all the highlight groups link to highlight groups already defined.

**Comment by yutkat** [comment]
I'm sorry. I thought nightfox didn't support it because it displayed like this.

![swappy-20221023-145949](https://user-images.githubusercontent.com/8683947/197376564-b1b0817c-d305-439c-b0b4-3a89ed005b3d.png)

But my plugin's loading order was wrong. Sorry to bother you.

```lua
	use({
		"folke/noice.nvim",
		after = { "nightfox.nvim" }, -- <- I needed this.
	})
```
