### ISSUE TITLE
How to change the configuration for concealed text when using Vimtex?

### ISSUE THREAD

**Issue by lubaroli** [EdenEast/nightfox.nvim#224]
Hello! I've recently started using Vimtex to write Latex files and one of the plugins features is to use conceal to substitute equations and symbols syntax by their respective characters. [Example here](https://github.com/lervag/vimtex-media/blob/main/img/syntax.png).

However, when this feature is enabled using Nightfox, the replaced symbols are stylised in dark-grey on a dark background, making them barely visible.

Could someone help me configuring this to render as normal text?

Thanks!

**Comment by EdenEast** [comment]
You can refer to the [syntax highlighting](https://github.com/EdenEast/nightfox.nvim#syntax-highlight-groups) section of the readme to figure out what the name of the highlight group. You can then override that highlight group.

I am guessing that the highlight group is `Conceal`. Here is an example of overriding it.

```lua
  require("nightfox").setup({
    groups = {
      all = {
        -- Some examples, make sure only to define Conceal once
        Conceal = { link = "Comment" }, -- link `Conceal` to another highlight group
        Conceal = { fg = "syntax.comment" }, -- link `Conceal` to a spec value
      }
    }
  })
```

**Comment by lubaroli** [comment]
Thanks so much for the quick answer!
