### ISSUE TITLE
Wrong colors with treesitter in php files on neovim 0.8.0

### ISSUE THREAD

**Issue by caplod** [EdenEast/nightfox.nvim#231]
## Description

After updating neovim from 0.7.2 to 0.8.0   the colors are wrong in php files.

**Screenshots**
Above neovim 0.8.0 
Below neovim 0.7.2

![highlights-in-php](https://user-images.githubusercontent.com/435070/200180068-8838315c-31d5-4bb3-87ee-bcf97d2790f4.jpg)

**Comment by EdenEast** [comment]
Can you check the difference between the highlight groups being used (see [here](https://github.com/EdenEast/nightfox.nvim/blob/main/readme.md#syntax-highlight-groups) for details on how). With 0.8, they changed how treesitter highlight groups work would like to see the difference between the two versions. I have seen some other changes.

**Comment by caplod** [comment]
It looks like they are the same?

neovim 0.7.2
![neovim 0 7 2](https://user-images.githubusercontent.com/435070/200757759-138d17ce-1eae-409f-821f-0bb25fde9b8c.jpg)

neovim 0.8.0
![neovim 0 8 0](https://user-images.githubusercontent.com/435070/200757811-27501533-c3dd-47ea-a161-2c844298826a.jpg)

**Comment by EdenEast** [comment]
Could you check the latest nightfox, as there has been a pass to treesitter highlight groups in #251.

**Comment by caplod** [comment]
unfortunately it didnt change

**Comment by EdenEast** [comment]
Closing this as this is an issue more with the treesitter php grammer then nightfox's definition of the treesitter highlight groups.
