### ISSUE TITLE
Change highlight of markdown code block

### ISSUE THREAD

**Issue by msvechla** [EdenEast/nightfox.nvim#233]
Hi, 

I tried to change the background color of a markdown code block, but I can not get it to work:

```lua
require('nightfox').setup({
    groups = {
	    all = {
                markdownCodeBlock = {bg = "#73daca"},
            }
    }
})
vim.cmd("colorscheme nightfox")
```

Any ideas on what I'm doing wrong here? Thanks!

**Comment by EdenEast** [comment]
I am not sure the highlight group that you are trying to change. You can find the what highlight group is being applied [here](https://github.com/EdenEast/nightfox.nvim#syntax-highlight-groups).

Here is an example of what I got.
![Screen Shot 2022-11-08 at 3 23 10 PM](https://user-images.githubusercontent.com/2746374/200667653-9d05d0ed-1263-46af-9ba0-8d6948295a9a.png)

Your configuration code block is correct. I would just comment on using `all` with a specific hex color. If you want you can use [templates](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#templates).

**Comment by EdenEast** [comment]
The closest thing you can get to this would be something like this:

```lua
require("nightfox").setup({
  groups = {
    all = {
      mkdCodeDelimiter = {fg = "palette.red.dim", bg = "bg0"},
      mkdCode = { fg = "syntax.string", bg = "bg0"}
    },
  },
})
```

I changed the delimiter to red to show the difference between the two highlight groups.

If you wanted syntax highlighting with something like treesitter then I dont think that is possible, as they use the normal treesitter highlight groups.
