### ISSUE TITLE
Light themes: highlight legibility for bitmap images in nvim-tree

### ISSUE THREAD

**Issue by colepeters** [EdenEast/nightfox.nvim#234]
## Description

Bitmap image filenames in nvim-tree appear to have an incorrect (or suboptimal) highlight group mapped to them, making them illegible:

<table>
<tr>
<td>
<img width="249" alt="image" src="https://user-images.githubusercontent.com/1713932/200648973-451a787f-560c-48ae-b4c1-cc5f45c27c24.png">
<p>with Dayfox</p>
</td>
<td>
<img width="241" alt="image" src="https://user-images.githubusercontent.com/1713932/200649616-bec43c52-388b-4c81-aa11-c625533da214.png">
<p>with Dawnfox</p>
</td>
</tr>
<table>

I'm not seeing this issue with any other filetypes currently. Guessing this is a lingering issue from the recent Treesitter changes!

## Behavior

**Expected behavior**
Bitmap image filenames should be legible.

**Screenshots**
See above

## Configuration

```lua
require('nightfox').setup({
  options = {
    transparent = false,
    modules = {
      cmp = true,
      gitsigns = true,
      lsp_trouble = true,
      native_lsp = true,
      nvimtree = true,
      telescope = true,
      treesitter = true,
    },
  },
  groups = {
    dayfox = {
      LineNr = { fg = 'bg4'},
    },
  },
})

vim.cmd('colorscheme dayfox')

```

**Comment by EdenEast** [comment]
This looks the image group is being set to white without checking if the palette is light or not. Will make a quick fix for that.
