### ISSUE TITLE
Custom lualine separators look out of place in inactive windows

### ISSUE THREAD

**Issue by AlxHnr** [EdenEast/nightfox.nvim#237]
## Description

It is pretty common to use the symbols ``/`` or ``/`` as the separators in lualine. They look broken when displayed in inactive windows. This change happened with 9df01a3.

## Behavior

**Expected behavior**

Lualine separators in inactive windows look subtle and don't pop into your face.

![before-default](https://user-images.githubusercontent.com/8235638/200901631-656e6146-ee26-4793-9709-461c4f023c9c.png)
![before](https://user-images.githubusercontent.com/8235638/200899694-56dc1809-1b9f-4c4f-8cc3-b17c99787414.png)

**Screenshots**

Lualine separators are out of place. Text in lualine_a and lualine_z is unreadable and needs more contrast.

![after-default](https://user-images.githubusercontent.com/8235638/200901663-6d9b2b04-c42b-4183-b07e-c0217e43d8a1.png)
![after](https://user-images.githubusercontent.com/8235638/200899699-1e3ade9d-ce17-4c68-a2fa-b1e208fc62f9.png)

## Configuration

**Reproduce**

1. Install the latest nightfox.nvim
2. Install lualine and make sure line separators show up in inactive windows:
```lua
local lualine_section_opts = { lualine_a = {{ 'mode' }} }
require('lualine').setup{ inactive_sections = lualine_section_opts }
```

## Additional info / context

Setup used for reproducing the issue:

* Nvim 0.8.0 with gnome-terminal (Fedora 36)
* Nvim 0.8.0 with  iTerm2 (MacOS)

**Comment by EdenEast** [comment]
I have created a pr to help address this. Please let me know if it solves your issue.

**Comment by AlxHnr** [comment]
Thanks! Works now.
