### ISSUE TITLE
Use compile file as default

### ISSUE THREAD

**Issue by EdenEast** [EdenEast/nightfox.nvim#240]
Taking a note from [catppuccin](https://github.com/catppuccin/nvim/pull/289) compile by default. This would help remove the precompiled files and simpler to understand.

Note this should be checked with vim support.

**Comment by nullchilly** [comment]
Note that it actually compile to lua bytecode now which is twice as fast :)

https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/lib/compiler.lua#L21
https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/init.lua#L77

![image](https://user-images.githubusercontent.com/56817415/201512305-507046cb-b89f-4af6-af91-e2769bed2c53.png)

**Comment by EdenEast** [comment]
Thanks for the note. I have a question that you might be able to help me with. I am trying to understand the caching. Looking at the implementation it the current date and compares to the date of the cached config hash and compiled function. 

How would this handle making a multiple config changes in the same day? My understanding is that it would compile and save the first change and write the current date. Then there is a second change made but the cached date is the same so it would not check if the config hashes are the same.

**Comment by EdenEast** [comment]
Ahh looking into more of how `debug.getinfo` works that the cur_date it built of the stat of the `git` plugin and the file that called setup. Since the stat of the file that calls setup should change when a user makes a change they will be different even when it is the same `date`.
