### ISSUE TITLE
Separate the color between "Popup bg" and  "visual selection bg" 

### ISSUE THREAD

**Issue by GenePg** [EdenEast/nightfox.nvim#242]
Can the customization separate the color between "Popup bg" and  "visual selection bg" on `sel0`.
It looks confuse to me when I'm selection words.

I think it should be gray on "Popup bg" and lighter gray on the "visual selection".

#### Popup bg in same vars
![Screen Shot 2022-11-15 at 20 39 51](https://user-images.githubusercontent.com/20477170/201921819-b7c04811-00bd-4de4-964f-5d89be41d247.png)

#### Selecting in visual mode
![Screen Shot 2022-11-15 at 20 39 37](https://user-images.githubusercontent.com/20477170/201921825-062bc430-5b13-4d59-b65e-688e1078ed86.png)

**Comment by EdenEast** [comment]
Could you clarify what you mean by the popup and visual selection. When talking about the popup menu this is the built in popup menu for completions.

![image](https://user-images.githubusercontent.com/2746374/202064409-4eea1306-c412-4320-ad5c-f786ae591b8c.png)

That and visual selection is the only two highlight groups that use `sel0`.

**Comment by GenePg** [comment]
Sorry, it's the [vim-illuminate](https://github.com/RRethy/vim-illuminate) display. I mess up.
