### ISSUE TITLE
Transparent and Dim Inactive settings not honored

### ISSUE THREAD

**Issue by vihu** [EdenEast/nightfox.nvim#245]
## Description

Unless I'm holding it wrong, the `transparent` and `dim_inactive` options don't seem to get honored.

## Behavior

I would imagine that setting `transparent` and `dim_inactive` should both be honored if the user has specified those in the settings.

**Screenshots**

![nightfox-bug](https://user-images.githubusercontent.com/3199183/202534365-0e83e43f-4121-405b-8213-7c7e41882899.gif)

## Configuration

Just using `minimal_init.lua` with the following options:

```lua
    require("nightfox").setup({
        options = {
            transparent = true,
            dim_inactive = true,
        }
    })

```

## Additional info / context

```bash
nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```bash
wezterm --version                                                                                                                                                                                            130 ↵
wezterm 20220905-102802-7d4b8249
```

**Comment by EdenEast** [comment]
Ah looks like with the recent change I am passing the wrong table to the config override. That will be a quick fix.
