### ISSUE TITLE
Better installation description

### ISSUE THREAD

**Issue by KodeToad** [EdenEast/nightfox.nvim#248]
A quick setup guide for deploying nightfox.
Specifically, I'm trying to install on Debian and I don't know where to start.
I'm not familiar enough with all the technologies to be able to easily install.
I've been using vim and linux for years but I like this theme and want to try it out.

I imagine readme.md would be suitable but a full setup guide per platform in the wiki would be useful

**Comment by EdenEast** [comment]
In the vim and neovim space plugins are usually handled by some sort of plugin manager. These are the projects that contain a full setup / installation guide. I can recommend a couple of plugin managers for you. 

## Vim
- [plug](https://github.com/junegunn/vim-plug) - The most used plugin manager written in vimscript
- [jetpack](https://github.com/tani/vim-jetpack) - Another plugin manager written in vimscript

## Neovim
- [paq](https://github.com/savq/paq-nvim) - A very small and simple plugin manager for neovim in lua
- [packer](https://github.com/wbthomason/packer.nvim) - A more featureful plugin manager in lua

**Comment by KodeToad** [comment]
This is really useful, thanks.
Perhaps it can be added to the readme just to save newbs time when figuring out how to proceed.
