### ISSUE TITLE
Custom bg color change?

### ISSUE THREAD

**Issue by tenorwill** [EdenEast/nightfox.nvim#250]
Apologies in advance, I'm new to Lua.

If i'm looking to make basic changes like background color changes, what is the process? I tried modifying `lua/nightfox/palette/nightfox.lua` and changing the `bg1` color to `#000000` but the change didn't take effect.
```lua
local palette = {
  -- relevant line:
  bg1     = "#000000", -- Default bg
```

The version of VIM I'm using is this:

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 13 2022 18:35:05)
macOS version - x86_64
```

I installed the plugin using Vundle:

```
Plugin 'EdenEast/nightfox.nvim'
colorscheme nightfox
```

After editing `nightfox.lua` is there anything else I need to modify for the change to take effect?

**Comment by EdenEast** [comment]
Hi @tenorwill, nightfox provides a `setup` function for you to provide your own customization's and tweaks. From your question I am guessing that you would like to change the background color of the `nightfox` style. Here is an example config.

```lua


require("nightfox").setup({
  palette = {         -- We want to change the palette
    nightfox = {      -- Changing the palette for nightfox
      bg1 = "#000000" -- Changing the default background color to black
    },
  },
})
```

If you are using a `vimscript` file, make sure to wrap the code section above in a `lua` block.

```vim
lua <<EOF
-- lua code section here
EOF
```

For a more detailed example of customizing nightfox see [this section of the readme](https://github.com/EdenEast/nightfox.nvim#customize-palettes-and-groups).

Changing the actual plugin is not recommended as any changes made to your local copy would be overridden when the plugin is updated. Let me know if you have any other questions

**Comment by tenorwill** [comment]
Thanks so much @EdenEast for the quick reply.

I tried adding the following to my `~/.config/nvim/init.vim` file and reloading vim (nvim) but the bg color change didn't take effect:

```lua
lua <<EOF
require("nightfox").setup({
  palette = {         -- We want to change the palette
    nightfox = {      -- Changing the palette for nightfox
      bg1 = "#000000" -- Changing the default background color to black
    },
  },
})
EOF
```
I tried some other plugins like `lualine` which did seem to work in the EOF block. Any further suggestions? Thanks again for your help.

**Comment by EdenEast** [comment]
Ah sorry I did a typo, it is `palettes` not `palette`.

```lua
require("nightfox").setup({
  palettes = {         -- We want to change the palette
    nightfox = {       -- Changing the palette for nightfox
      bg1 = "#000000", -- Changing the default background color to black
    },
  },
})
```

**Comment by tenorwill** [comment]
Awesome! That was it. Thanks for your help, great work on the nightfox theme!
