### ISSUE TITLE
Cache never invalidates when changing config or updating the plugin

### ISSUE THREAD

**Issue by oxalica** [EdenEast/nightfox.nvim#253]
## Description

Currently we relies on mtime, which never work with content-address-like system like [Nix](https://nixos.org). It resets mtime of all sources and programs and relies purely on hashes to be pure and deterministic.
https://github.com/EdenEast/nightfox.nvim/blob/741366250cff3aa7b85d6588ffc9db60ebbfdcc9/lua/nightfox/init.lua#L82-L84

We should better ONLY use hash of config, plugin version, and nvim version to determine cache validity. Note that this is still kind of fragile, since the Lua version, user patches for the plugin or nvim, and a lot of other things cannot be taking into account.

Personally, I'd rather to have an option to disable the fragile cache. It's already fast to setup without any "compiled" cache.

## Behavior

**Expected behavior**
1. Have ability to disable the cache.
2. Use ONLY hash to track cache validity rather than mtime.

## Additional info / context

I'm on NixOS and using Nix to manage all plugins.

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld
```

**Comment by EdenEast** [comment]
I had an idea to [fix](https://github.com/catppuccin/nvim/issues/348#issuecomment-1321203167) this but have not got around to it. Thinking of going the workflow route.

**Comment by oxalica** [comment]
#254 cannot fully resolve the environment or configuration change issue (vimrc is also in nix store).

I'd still ask for an option to fully disable the cache. Currently I have to
```lua
vim.fn.delete(vim.fn.stdpath("cache") .. "/nightfox/stat")
require("nightfox").setup {}
```

**Comment by EdenEast** [comment]
I created a PR that hashes the file name as well as the mine time. This will handle files in the `/nix/store`. Let me know if this PR resolves you issue with the nix store.

**Comment by nullchilly** [comment]
@EdenEast https://github.com/lewis6991/impatient.nvim/issues/42

impatient.nvim's hash function also take size into account

```lua
local function hash(modpath)
  local stat = fs_stat(modpath)
  if stat then
    return stat.mtime.sec..stat.mtime.nsec..stat.size
  end
  error('Could not hash '..modpath)
end
```
