### ISSUE TITLE
tmux status bar text need a higher contrast

### ISSUE THREAD

**Issue by eatgrass** [EdenEast/nightfox.nvim#256]
## Description
I tried 'nightfox' and 'dayfox' themes for tmux, the text in the status bar are hard to see, as you can see in the following screenshots.

**Screenshots**
dayfox
<img width="752" alt="image" src="https://user-images.githubusercontent.com/2351076/204086662-0c27c003-bf57-46df-9fbd-d7180b9c849a.png">

nightfox
<img width="734" alt="image" src="https://user-images.githubusercontent.com/2351076/204086736-9abf6848-95e3-4c04-a18a-a9b0bfcbc397.png">

## Configuration
https://github.com/edeneast/nightfox.nvim/raw/main/extra/dayfox/nightfox_tmux.tmux

https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_tmux.tmux

**Comment by EdenEast** [comment]
Resolved by #264
