### ISSUE TITLE
Error when running :NightfoxCompile in Neovim

### ISSUE THREAD

**Issue by mile-stojakovic** [EdenEast/nightfox.nvim#259]
## Description
Running `:NightfoxCompile` upon obtaining a fresh installation of Nightfox on Neovim gives an error.

## Behavior

**Expected behavior**
The Lua code should compile and the theme should be available for use shortly after.

**Screenshots**
![image](https://user-images.githubusercontent.com/91222165/204155380-3e30a23b-a6f1-4794-b0a7-33fe24cf6010.png)

## Configuration

**Reproduce**

These instructions are specifically for Vim-Plug. I have tried to install Nightfox using Packer as well, but the error persists.

1. Install Neovim.
2. create a directory "colors" in `~/.config/nvim`.
3. create a directory "autoload" in `~/.config/nvim`.
4. Install Vim-Plug into `autoload`.
5. create an `init.vim` file with the contents of "minimal_init" below in `~/.config/nvim`.
6. open `init.vim` and run `:PlugInstall`.
7. run `:NightfoxCompile` or `:colorscheme nightfox`.

<details>
<summary>minimal_init.vim</summary>

```vim
call plug#begin('~/.config/nvim/colors')
Plug 'EdenEast/nightfox.nvim'
call plug#end()
```

</details>

## Additional info / context

I am using Neovim 0.6.1 on Ubuntu 22.04 LTS. The `$TERM` variable is `xterm-256color`.

**Comment by nullchilly** [comment]
Doesn't seem like `vim.notify` is supported in neovim 0.6.1

The latest version is 0.8.1, consider updating?

**Comment by EdenEast** [comment]
Yes it does look like the neovim needs to be updated. Currently I have the requirements section saying that it requires 0.5 but that has not been re-evaluated in a while. I think I would say that it supports 0.8. I say that because of the treesitter changes. The theme will work with 0.7 as it is but there will be the invalid group message. Updating the required section.

**Comment by mile-stojakovic** [comment]
That's it. I installed with just apt, but for some reason the version that apt had was outdated. Installing the .deb file for 0.8.1 worked perfectly. Thanks a lot and sorry for the inconvenience!

**Comment by EdenEast** [comment]
Np, it was a good reminder to check the required section.
