### ISSUE TITLE
How to set/override hover background to transparent?

### ISSUE THREAD

**Issue by MarWeUMR** [EdenEast/nightfox.nvim#265]
Hi there,

setting the background color of a hover window from e.g. `lsp.buf.hover` works, when I use this setting:
```
require("nightfox").setup({
  groups = {
    carbonfox = {
	NormalFloat = { link = "DiffAdd" },
        -- NormalFloat = { bg = "#73daca" }, -- this works as well
    },
  },
  options = {
    transparent = true,
    ...
  },
})
vim.cmd("colorscheme carbonfox")
...
```

What I can't get to work is a transparent background like e.g. telescope or neotree etc.
For instance, linking to `Normal` does not work. That would have been, what I expected to be neccessary, is this correct?
Changes to `NormalFloat` effect the look of telescope as I would expect them to by the way. What am I missing here?

I'm not sure, if this is an issue of me being too dump to set things up correctly, or maybe something in my config messes with the transparency setting...

This is what it looks like without modification:
<img width="383" alt="Bildschirm­foto 2022-12-01 um 09 59 07" src="https://user-images.githubusercontent.com/27370794/205010046-8db14847-3fa0-4ebc-85e3-4edeaff30591.png">

...using some setting takes effect:
<img width="359" alt="Bildschirm­foto 2022-12-01 um 10 00 30" src="https://user-images.githubusercontent.com/27370794/205010369-63d3db1c-a3b2-4966-9f0d-7d5edd060513.png">

What I would like to achive, the same style as in telescope:

<img width="696" alt="Bildschirm­foto 2022-12-01 um 10 03 12" src="https://user-images.githubusercontent.com/27370794/205010963-1910f2c4-91ab-4066-8dde-9d895911ba10.png">

**Comment by EdenEast** [comment]
Have you tried to get the background to `NONE`?

```lua
require("nightfox").setup({
  options = {
    transparent = true,
  },
  groups = {
    all = {
      NormalFloat = { bg = "NONE" },
    },
  },
})
```
![Screen Shot 2022-12-01 at 2 17 40 PM](https://user-images.githubusercontent.com/2746374/205140606-83eec2db-986b-4912-8457-5dcb76c3df89.png)
