### ISSUE TITLE
Updated init.vim and Nightfox broke

### ISSUE THREAD

**Issue by ChristopherKRad** [EdenEast/nightfox.nvim#271]
## Description

Ran :PlugClean to remove a few plugs i was not using - after plug clean I began receiving the following errors:

- On opening neovim:

>Error detected while processing /home/chris/.config/nvim/init.vim:
>line    8:
>E185: Cannot find color scheme 'nightfox'
>Press ENTER or type command to continue`

- On :Nightfox compile (or sourcing init.vim)

>E5108: Error executing lua vim/_editor.lua:404: Chunk is not an array with one or two strings
>stack traceback:
>        [C]: in function 'nvim_echo'
>        vim/_editor.lua:404: in function 'notify'
>        ...nfig/nvim/plugged/nightfox.nvim/lua/nightfox/lib/log.lua:11: in function 'warn'
>        .../nightfox.nvim/lua/nightfox/group/modules/treesitter.lua:9: in function 'get'
>        ...config/nvim/plugged/nightfox.nvim/lua/nightfox/group.lua:33: in function 'from'
>        ...nvim/plugged/nightfox.nvim/lua/nightfox/lib/compiler.lua:27: in function 'compile'
>        ....config/nvim/plugged/nightfox.nvim/lua/nightfox/init.lua:31: in function 'compile'
>        [string ":lua"]:1: in main chunk

What's interesting is I don't see :NightfoxStatus nor :NightfoxClean

## Behavior

**Expected behavior**
Colors and feline should render with colorscheme defined in init.vim

**Screenshots**
![image](https://user-images.githubusercontent.com/97244810/205847738-880b06d5-c181-49c2-ab30-050ecf162336.png)

## Additional info / context

NVIM v0.7.2

Any assistance is greatly appreciated!

**Comment by EdenEast** [comment]
Yes this is correct. This plugin supports the latest version of neovim updating neovim will resolve your issue.

**Comment by ChristopherKRad** [comment]
Understood - will do.

If there's a particular version you'd recommend please let me know.

Big fan of your work and the project! @EdenEast

**Comment by EdenEast** [comment]
This will support any neovim version >= `0.8.0`.

**Comment by Diablo-D3** [comment]
Can you tag a commit that is the last one that supports 0.7.x?

**Comment by EdenEast** [comment]
I have bisected nightfox and created the tagged `nvim/0.7.x`.
