### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by max397574** [EdenEast/nightfox.nvim#277]
have you got any benchmarks with the compiled and uncompiled theme?
I wonder how big the difference is

**Comment by olimorris** [comment]
I've implemented a lot of the features that @EdenEast and @nullchilly have pioneered in their themes, in my own colorscheme. The impact of compilation is significant. I've gone from c. `3.50 ms` uncompiled to `<0.5 ms`. The genius is caching it to disk as bytecode and the checking of the config hash to determine if it needs to be regenerated.

I think we'll begin to see a lot of other plugins moving in this direction.
