### ISSUE TITLE
Nightfox.nvim not compiling

### ISSUE THREAD

**Issue by p4nchit0z** [EdenEast/nightfox.nvim#278]
Hi, I'm using Neovim 0.8 via [AstroVim](https://github.com/AstroNvim/AstroNvim). I used to use 'Carbonfox' theme and I never had problems with it. However, I updated some things and now Carbonfox theme throws the error shown in the image below. I tried this with other themes included here like Nightfox or Duskfox and this error persists. Now, _and this is the important thing_, I know you could blame AstroVim for not recognizing it or being missconfigured. However, it works perfectly with any other theme I have been testing, like [oxocarbon](https://github.com/nyoom-engineering/oxocarbon.nvim) or [catppuccin](https://github.com/catppuccin/nvim), among others. In other words, this only happens with Nightfox's themes.

![image](https://user-images.githubusercontent.com/31874167/209547789-c15740e6-8fc1-42ef-b362-40cdf4ad250e.png)
I suspect the error comes from the functions inside the red rectangle.

I really, really love Carbonfox and just wanted to report his issue. 
Cheers

**Comment by EdenEast** [comment]
It looks like the failure looks like it is coming from nvim-notify, saying that strings can't have new lines. I redid the logging for nightfox let me know if your get the same error.

**Comment by p4nchit0z** [comment]
Hi, 
Thanks for your quick reply. And now it's working!

![image](https://user-images.githubusercontent.com/31874167/209589335-e3871734-ad24-48cc-b954-ee03c60badef.png)

Solved and thank you!

P.S.: I still find Carbonfox the best theme ever.
