### ISSUE TITLE
Fish extra does not load

### ISSUE THREAD

**Issue by Swoogan** [EdenEast/nightfox.nvim#28]
The Fish extra cannot be source due to invalid tokens. The issue is a token that was not replaced when templating is executed:
Fixes this issue: https://github.com/EdenEast/nightfox.nvim/blob/65ad04388b9885a9a8b96dbba611489a272451b0/extra/nightfox/nightfox_fish.fish#L10

**Comment by EdenEast** [comment]
Good catch that should be changed to `${magenta}`
