### ISSUE TITLE
make carbonfox look more like the original

### ISSUE THREAD

**Issue by luxus** [EdenEast/nightfox.nvim#289]
hi,
congratulation to 3.0
do you mind a PR to make carbonfox look like https://github.com/nyoom-engineering/nyoom.nvim ? Or do you prefer how it looks now?

I would love to have oxocarbon in nightfox.nvim :)

I forked your repo and tried a little bit.
The first thing I notice is that, for example, folders for neotree are blue, can I overwrite it for carbonfox in its fox Lua? (I know that I can overwrite it in my config via groups, but I wonder if I could overwrite it just in the one fox in nightfox.nvim directly)
maybe I just overlooked it in the usage.md (very tired and will take a look with fresh eyes tomorrow)

**Comment by EdenEast** [comment]
Carbonfox is an adaptation and applying those colors to nightfox's palette concept. You can change the highlight group for just one fox in the config.

```lua
require("nightfox").setup({
  groups = {
    carbonfox = {
      SomeGroup = { fg = "palette.blue" },
    },
  },
})
```

This will only change the group for that theme.
