### ISSUE TITLE
Support highlight-blend

### ISSUE THREAD

**Issue by danilax999** [EdenEast/nightfox.nvim#293]
I would like to set the blend option for some highlight groups. For example:
```lua
require'nightfox'.setup {
  groups = {
    all = {
      Normal = { fg = 'palette.fg1', bg = 'palette.bg1', blend = 15 }
    }
  }
}
```

**Comment by EdenEast** [comment]
Are you refering to `:h highlight-blend`?

**Comment by danilax999** [comment]
For some plugins I was able to specify window blend option only in highlight groups.
telescope.nvim uses Normal highlight-group for Previewer and Results panes, so they are become transparent only after setting highlight-blend for the Normal group. Also, nvim-notify and noice.nvim links their hi-groups to the Normal group, thus they are not transparent.

Before `:hi Normal blend=15`:
![2023-01-18_16-58-01](https://user-images.githubusercontent.com/75566563/213226078-ec806890-7cbb-433b-bbed-abe720dbafe2.jpg)

After:
![2023-01-18_16-58-39](https://user-images.githubusercontent.com/75566563/213226413-6ab33b72-8b46-4652-ba47-a985c8753a6d.jpg)

**Comment by EdenEast** [comment]
The issue with winblend was resolved in commit https://github.com/EdenEast/nightfox.nvim/commit/773fd00919fdd737569906948a9a527fd0127465.
