### ISSUE TITLE
Ability to create new highlight based on existing one. 

### ISSUE THREAD

**Issue by JoseConseco** [EdenEast/nightfox.nvim#294]
### Is your feature request related to a problem? Please describe.

Lets say plugin 'indent line'  uses highlight `indent_hl`  which is set to 'red'.
For to match  `indent_hl` color with eg. nightfox - we set  :  
 `indent_hl`  =  nightfox.background - 10%      -- use theme normal highlight, but make it 10% darker.
Thing is if we set to dayfox  (or any other colorscheme)  then above 'indent_hl' wont match it,  so we would have to declare `indent_hl` for each theme separately. 

### Describe the solution you'd like

I  created code,  that will update any highlight on theme change. 
```
on theme change autocmd
  highlight_target = hightlight_source +/- brightness or contrast
```
Would u be willing to include it in nightfox? It is using nightfox.color lib, thus that is why I with it was integrated in nightfox.

### Describe alternatives you've considered

Made my own script.  I do not think there is anything like this.

### Additional context

Here is the code I'm using - 
`https://github.com/JoseConseco/nvim_config/blob/master/lua/hl_manager.lua`

End example usages:

- create NormalNC highlight, that is -5 darker than current theme background (color is updated on theme change)

```lua
local hl_manager = require "hl_manager"
hl_manager.highlight_from_src("NormalNC", "Normal", {bg = -5})
```

- use existing  WinBar highlight,  but update its  foreground to be same as normal hl but 14% darker, and background 2% lighter ( update on theme change)

```lua
hl_manager.match_hl_to_highlight("WinBar", "Normal", {fg = -14, bg = 2})
```

- link  Whitespace highlight,  to "Comment" highlight  (updated after theme change, thus u are sure new theme won't override Whitespace to something other  - normal vim hl_link way does not guarantee this) 

```lua
hl_manager.highlight_link("Whitespace", "Comment")
```

 - match_color_to_highlight - it will take input color, and adjust it brightness to `reference_hl` -> finally outputing new highlight based on that color. Used below  for 'nvim-ts-rainbow'  plugin -  which gives random color to matching brackets.  With `match_color_to_highlight`  each bracket brightness will automatically match dark/light theme   (dark brackets for light theme,  bright brackets for dark theme -  uses '@punct.bracket' as reference for output  absolute brightness) 
  ```lua
    local hl_manager = require "hl_manager"
      hl_manager.match_color_to_highlight("#ebcb8b", "@punct.bracket", "rainbowcol1", "foreground")
      hl_manager.match_color_to_highlight("#a3be8c", "@punct.bracket", "rainbowcol2", "foreground")
      hl_manager.match_color_to_highlight("#88c0d0", "@punct.bracket", "rainbowcol3", "foreground")
      hl_manager.match_color_to_highlight("#6ea1ec", "@punct.bracket", "rainbowcol4", "foreground")
      hl_manager.match_color_to_highlight("#b48ead", "@punct.bracket", "rainbowcol5", "foreground")
      hl_manager.match_color_to_highlight("#df717a", "@punct.bracket", "rainbowcol6", "foreground")
      hl_manager.match_color_to_highlight("#d08770", "@punct.bracket", "rainbowcol7", "foreground")

```

**Comment by Sosyetekadir** [comment]
- [ ]
