### ISSUE TITLE
bug: Failed when start vim 8.2

### ISSUE THREAD

**Issue by nkta3m** [EdenEast/nightfox.nvim#295]
### Neovim version (nvim -v)

vim 8.2

### Operating system/version

Debian 11

### Describe the bug

[string "vim chunk"]:2: attempt to index field 'g' (a nil value) when start vim
![2023-01-11 15_19_03-Window](https://user-images.githubusercontent.com/13484700/211742746-1cce93e2-ab93-4f0f-a8cf-c793efaad466.png)
![2023-01-11 15_19_44-](https://user-images.githubusercontent.com/13484700/211742768-04c1ddec-214d-4b5d-8522-4f6467c98080.png)

### Steps To Reproduce

1. colorscheme carbonfox
2. start vim

### Expected Behavior

correct display theme

**Comment by EdenEast** [comment]
It looks like you cant access `vim.g` which is how globals are checked in lua.

What is the result of trying to call `:lua vim.g.nightfox_debug = true` ? Does this fail?

Also do you have the help `:help lua-vim-variables`?

**Comment by nkta3m** [comment]
![2023-01-12 08_36_35-设置](https://user-images.githubusercontent.com/13484700/211948243-451711d4-4797-4174-ba0b-868ff579927d.png)
when input :help lua-vim-variables
return "sorry, no help for lua-vim-variables"

**Comment by EdenEast** [comment]
It might be that `vim.g` is only in vim 9.

**Comment by nkta3m** [comment]
You are right. i use vim9 is OK.
