### ISSUE TITLE
How to make the floating window to transprant ?

### ISSUE THREAD

**Issue by zengshenggit** [EdenEast/nightfox.nvim#297]
As the title asked, is there a  style option that can set floating window to transprant?
Emm... i want to make all windows to transprant, not just normal window but also  floating window.

**Comment by EdenEast** [comment]
Setting something as `transparent` is really just not setting it at all. You can do this by setting the background to `NONE`.

```lua
require("nightfox").setup({
  options = {
    transparent = true,
  },
  groups = {
    all = {
      NormalFloat = { fg = "fg1", bg = "NONE" }
    },
  },
})
```

**Comment by zengshenggit** [comment]
Okay, thanks a lot.

**Comment by zengshenggit** [comment]
Close

**Comment by zengshenggit** [comment]
Closed
