### ISSUE TITLE
Transparent cmp completion window and transparent docs

### ISSUE THREAD

**Issue by lucascool12** [EdenEast/nightfox.nvim#299]
I've been unable to get the cmp completion window transparent.

```lua

require'nightfox'.setup{
  options = {
    transparent = false,
  },
  groups = {
    all = {
      Pmenu = { bg = "NONE" },
      NormalFloat = { bg = "NONE" },
      WildMenu = { bg = "NONE" },
    },
  },
}
vim.cmd("colorscheme terafox")
vim.opt.pumblend = 35
vim.opt.winblend = 35
vim.cmd("highlight Pmenu guibg=NONE")
vim.cmd("highligh NormalFloat guibg=NONE")
```
This is what I've tried but it doens't work.
Commenting out vim.cmd("colorscheme terafox") makes the completion window and doc transparent.
Setting transparent in options to true does not change the completion window nor docs.

**Comment by EdenEast** [comment]
cmp uses the highlight group `NormalFloat` as the base for the completion popup and documentation. I was able to get this result with the following config.

```lua
require("nightfox").setup({
  options = {
    transparent = true,
  },
  groups = {
    all = {
      NormalFloat = { fg = "fg1", bg = "NONE", },
    },
  },
})
```

![image](https://user-images.githubusercontent.com/2746374/212526866-e6db46ca-d397-4e70-bd97-532772caba63.png)

**Comment by lucascool12** [comment]
Thanks for the reply, but it seems just saying transparent didn't convey what I meant.
This is what I'm trying to get with nightfox enabled (getting the text under the completion window to peak through):
![nvim_blend](https://user-images.githubusercontent.com/71119084/212531742-7e43962e-69d7-4e93-9642-2b9792c59e17.png)

I can achieve the above by setting:

```lua
vim.opt.pumblend = 14
vim.opt.winblend = 14
vim.cmd("highlight Pmenu guibg=NONE")
vim.cmd("highligh NormalFloat guibg=NONE")
```

But I've been unable to achieve this with nightfox enabled.

**Comment by lucascool12** [comment]
The example above is a bit hard to see, here is an exaggerated version, with pumblend = 40:
![nvim_blend2](https://user-images.githubusercontent.com/71119084/212532555-06352529-2a8d-4217-8490-5d484429a641.png)

Also it seems winblend does not matter here.

**Comment by EdenEast** [comment]
Finally found the issue. It looks like the highlight group `NormalNC` needs to be also set to `NONE`.

![image](https://user-images.githubusercontent.com/2746374/212783078-efff7736-0259-4a35-92b3-a86550af5d9e.png)

```lua
require("nightfox").setup({
  options = {
    transparent = true,
    modules = {
      cmp = false,
    },
  },
  groups = {
    all = {
      NormalFloat = { bg = "bg1" },
      NormalNC = { bg = "NONE" },
    },
  },
})
```

**Comment by lucascool12** [comment]
Thanks!
