### ISSUE TITLE
Bumping Red color

### ISSUE THREAD

**Issue by JoseConseco** [EdenEast/nightfox.nvim#3]
Thanks for great theme EdenEast!.  I just wanted suggest bumping red color a bit to : `red="#dc6959"` 
new
![image](https://user-images.githubusercontent.com/13521338/129900521-a5b4ddca-70c6-4531-ad96-5ef00c0897ef.png)
old:
![image](https://user-images.githubusercontent.com/13521338/129900418-492ae5a1-65a9-4d12-8587-c18d590e7bfe.png)

Its small change but IMO default red is bit to dim, compared to neighbor area. I only tested default  style.
Black and white  version where its easier to see brightness differences (its easier to see that old red is blending bit much into background) :
![image](https://user-images.githubusercontent.com/13521338/129901530-e65684c8-6826-409d-8f9d-2a09e440290a.png)

**Comment by EdenEast** [comment]
Thanks for your suggestion. All the styles define brigher colors. The current bright red is defined as `#D6616B`. I find `#dc6959` a bit too orange.

You can override any of nightfox's colors with the `nightfox_colors` variable. An example is:

```lua
vim.g.nightfox_colors = {
    red = "#D6616B",
}

require("nightfox").set()
````

I will keep this in my config for a bit and see how it goes.

**Comment by JoseConseco** [comment]
Thank. The override is what I have done. I just thought  this change could be useful for other users too.
