### ISSUE TITLE
cmp color

### ISSUE THREAD

**Issue by dnxxymcj** [EdenEast/nightfox.nvim#308]
Hello, how to make the right red circle the same as the left? it's too dark.
<img width="681" alt="1" src="https://user-images.githubusercontent.com/7660888/218287903-d84e0685-18a1-499e-ae6b-48a9bdb85e41.png">

**Comment by EdenEast** [comment]
The highlight group used is `NormalFloat`. You can change which highlight groups are applied in cmp's setup function for example:

```lua
local cmp = require("cmp")
cmp.setup({
  window = {
    documentation = cmp.config.window.bordered({
      winhighlight = "Normal:Pmenu,FloatBorder:Pmenu,CursorLine:PmenuSel,Search:None",
    }),
  },
})
```

This changes the highlight group to use Pmenu.

**Comment by dnxxymcj** [comment]
> The highlight group used is `NormalFloat`. You can change which highlight groups are applied in cmp's setup function for example:
> 
> ```lua
> local cmp = require("cmp")
> cmp.setup({
>   window = {
>     documentation = cmp.config.window.bordered({
>       winhighlight = "Normal:Pmenu,FloatBorder:Pmenu,CursorLine:PmenuSel,Search:None",
>     }),
>   },
> })
> ```
> 
> This changes the highlight group to use Pmenu.

thanks
