### ISSUE TITLE
feature request: inverse matches

### ISSUE THREAD

**Issue by quantum-booty** [EdenEast/nightfox.nvim#31]
In https://github.com/srcery-colors/srcery-vim there is an option to inverse the colour of matches and match parenthesis of treesitter-highlight module or a / search:
![image](https://user-images.githubusercontent.com/28958399/132089644-ed880bd9-bcf5-425a-9059-a3af1840d666.png)
![image](https://user-images.githubusercontent.com/28958399/132089638-e21d212e-b698-4f76-9eae-f55bc302b636.png)

Could you please add a similar feature to nightfox? Because I think this can improve visibility of these matches, as you see its currently a bit hard to see without inverse colours.
![image](https://user-images.githubusercontent.com/28958399/132089729-be3dc971-623e-4fdf-9f21-bd83dde60db9.png)

**Comment by EdenEast** [comment]
I have created a PR that implements this feature. Is this what you were looking for?. I am unsure as this is something that I would not use.

**Comment by quantum-booty** [comment]
@EdenEast Thank you very much for implementing this! This is exactly what I'm looking for.
