### ISSUE TITLE
bug: Brackets under cursorline are not highlighted correctly

### ISSUE THREAD

**Issue by norflin321** [EdenEast/nightfox.nvim#313]
### Neovim version (nvim -v)

0.8.2

### Operating system/version

MacOS Ventura 13.0

### Describe the bug

Brackets under cursorline are not highlighted correctly
<img width="873" alt="Screenshot 2023-02-20 at 7 31 44 AM" src="https://user-images.githubusercontent.com/33498670/220010161-27a0b3be-2b86-4000-bb21-265c7fc94000.png">

### Steps To Reproduce

1. set cursorline
2. move cursor on a line with brackets

### Expected Behavior

I previously used [gruvbox](https://github.com/ellisonleao/gruvbox.nvim) theme, which does not have the same problem on exactly the same setup
<img width="873" alt="Screenshot 2023-02-20 at 7 31 29 AM" src="https://user-images.githubusercontent.com/33498670/220010133-ac4da766-a23f-45d7-b90d-6322509e2f5b.png">

**Comment by EdenEast** [comment]
I am not able to reproduce your issues. 

![image](https://user-images.githubusercontent.com/2746374/220233024-02e3b15d-7ec7-425d-8c32-fd78581f99da.png)

- Do you have a minimal configuration that reproduces the issue?
- What terminal are use using?
  - Does this happen on multiple terminals?

**Comment by norflin321** [comment]
I only have this bug with typescript, on both kitty and default macos terminals. It also happens with a completely empty vimrc

**Comment by nullchilly** [comment]
Seems like an issue with your italic font, try to comment out [these 3 lines](https://github.com/norflin321/dots/blob/41fef048ae093610c6034493b10a5af107cdb666/kitty/kitty.conf#L4-L6) in your kitty config

Also [try this](https://gist.github.com/gutoyr/4192af1aced7a1b555df06bd3781a722) just in case you use tmux

**Comment by norflin321** [comment]
<img width="1559" alt="Screenshot 2023-03-03 at 12 33 02 PM" src="https://user-images.githubusercontent.com/33498670/222687734-2d04d11b-e7d6-4571-83da-338b550aeace.png">

- I can confirm that this is not a font issue, I have tried multiple fonts and don't use tmux.
- This problem occurs both in the kitty terminal and in the [neovide](https://github.com/neovide/neovide) gui. It resolves after i call command: `hi typescriptParens guifg=NONE guibg=NONE`.

<img width="531" alt="Screenshot 2023-03-03 at 12 43 41 PM" src="https://user-images.githubusercontent.com/33498670/222687817-4167c16d-edc8-42bd-868d-3e12e80ef3fc.png">

but for some reason this solution does not work if i put this command at the very end of vimrc.

**Comment by nullchilly** [comment]
@norflin321 Try to remove this line:

```vim
Plug 'maxmellon/vim-jsx-pretty'
```

**Comment by norflin321** [comment]
thanks for the advice, unfortunately it did not help. And I tested it with an empty vimrc before, the error persists.
<img width="1555" alt="Screenshot 2023-03-03 at 6 04 19 PM" src="https://user-images.githubusercontent.com/33498670/222758460-718aeaf1-8771-43de-a872-3e6e41796f98.png">

**Comment by nullchilly** [comment]
typescriptParens can only be found in vim-jsx-pretty, not sure if you are actually running an empty vimrc

**Comment by nullchilly** [comment]
My apologies, it is set here

```lua
:verbose hi typescriptParens                                                                      
typescriptParens xxx links to Normal                                                              
        Last set from /usr/share/nvim/runtime/syntax/shared/typescriptcommon.vim line 1979 
```

**Comment by nullchilly** [comment]
@norflin321 What's the output of `:hi typescriptParens`

And can you send a tsx snippet with your issue?

**Comment by nullchilly** [comment]
@norflin321 I opened https://github.com/norflin321/dots/pull/1 to fix your problem, hope it helps!

**Comment by norflin321** [comment]
thank you a lot, it solved the issue!
i appreciate your help 😄
