### ISSUE TITLE
Bug: YAML Highlighting does not differentiate between fields and values

### ISSUE THREAD

**Issue by chrisgrieser** [EdenEast/nightfox.nvim#314]
### Neovim version (nvim -v)

neovim 0.8.3 (homebrew)

### Operating system/version

macOS 13.2 (M1)

### Describe the bug

It's pretty much exactly the same issue already described in #274, which still occurs for me with the latest commit of nightfox.

### Steps To Reproduce

Since the remainder of this bug report would pretty much be a duplication the report from #274, I hope it is okay that I do not repeat what was already well-laid out by the issues op.

### Expected Behavior

(see above)

**Comment by chrisgrieser** [comment]
I think I found (part of) the cause: `@field.yaml` seems to be cleared. 

I went through my config, and I do have a line running `highlight clear` before setting the color scheme. Removing that line fixed the issue.

Now that isn't just a random config from me, but rather the [recommended solution for problem with lazy.nvim](https://github.com/folke/lazy.nvim/issues/40#issuecomment-1360412456).

Though the problem described in the issue does not occur with nightfox as color scheme, so I removed the line. I am leaving this issue open, since it might still be relevant to look into this

**Comment by nullchilly** [comment]
Can you run `:lua vim.g.nightfox_debug = true require("nightfo
x").compile()`

Then check if `~/.cache/nvim/nightfox/dawnfox_compiled.lua` contains `@field.yaml`?

**Comment by chrisgrieser** [comment]
okay, this is weird. Now the error does not occur anymore 🤔 
maybe some caching error? I dunno.

will report back if it re-occurs...

**Comment by EdenEast** [comment]
If the error happens again and you can reproduce the cache error, please let me know.
