### ISSUE TITLE
feature: Dim Inactive Exceptions

### ISSUE THREAD

**Issue by aemonge** [EdenEast/nightfox.nvim#343]
### Is your feature request related to a problem? Please describe.

Not a problem, but an Idea.

### Describe the solution you'd like

I would love to have some inactive expections, mostly the `:terminal` buffers. 

### Describe alternatives you've considered

Haven't consider alternatives

**Comment by EdenEast** [comment]
`dim_inactive` is a toggle that will set `NormalNC` to `bg0` instead of just linking to `Normal`. `NormalNC` does not distinguish between types of buffers.

**Comment by aemonge** [comment]
For other that might look for this, we can use `levouh/tint.nvim`
