### ISSUE TITLE
How to access the current palette

### ISSUE THREAD

**Issue by prss-ad** [EdenEast/nightfox.nvim#358]
Hi, i love this plugin. Really. 
It has almost everything needed.

I just have a question: How can i access the current palette colors?
I looked everywhere and i can't find a way to do that. It might be obvious but i could'nt.
That would make much easier using these colors elsewhere .

Thanks for the support and the great work!
best regards

**Comment by EdenEast** [comment]
Are you referring to [this](https://github.com/EdenEast/nightfox.nvim#palettes). This will let you either get all the palettes defined in nightfox or a specific.

**Comment by prss-ad** [comment]
I'm really sorry. I did see that and tried it. I tried it and somehow  got the idea that it returned the original palette. Don't know what i did to get that idea.  One of those nights i guess. 
Thank you very much.
Best regards.
