### ISSUE TITLE
Nordfox background colour has changed 

### ISSUE THREAD

**Issue by eggbean** [EdenEast/nightfox.nvim#359]
### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Pengwin (Debian)/WSL

### Describe the bug

![image](https://github.com/EdenEast/nightfox.nvim/assets/815311/fa7ce1b7-d1dd-4f23-84d1-a5d9ab375f6b)

The background colour of Nordfox seems to have changed to a brown tint. On the right you can see a tmux pane where I have changed the terminal background colour to match Norfox, so a tmux split like this used to appear as seamless. You can also see at the extreme left and top that the terminal background colour can be seem, which was a seamless transition before. I can't figure out what's going on.

### Steps To Reproduce

1. Start nvim with nordfox enabled.

### Expected Behavior

Nordfox used to have the same background colour as the pane on the right of the picture.

### Repro

```Lua
I don't know what this is.
```

**Comment by bleczz** [comment]
Do you have termguicolors set to true?

**Comment by eggbean** [comment]
Yes. I forgot that this was happening as at some point it stopped. It was only occurring on my local laptop and not cloud instances which have the same dotfiles. I'll close for now. Cheers.
