### ISSUE TITLE
bug: Wrong highlight in Telescope prompt

### ISSUE THREAD

**Issue by arthurx07** [EdenEast/nightfox.nvim#371]
### Neovim version (nvim -v)

0.9.1

### Operating system/version

Gentoo Linux

### Describe the bug

I am using the carbonfox colorscheme and have setup transparency with: 
`options = { transparent = true, }, groups = { all = { NormalFloat = { bg = "NONE" } } },`

Everything is working fine, except that when opening Telescope.nvim its prompt is highlighted when (i think) it shouldn't be (and I prefer it not to be). I have tested with `:hi TelescopeBorder guibg=NONE` but it hasn't worked. 

Maybe this is more of a question than a bug, but how could I do it for it to stop behaving like that? Thanks

PD: My config is very minimal, and I'm using the defaults on Telescope.nvim and nightfox (except from transparency).

![image](https://github.com/EdenEast/nightfox.nvim/assets/83729186/6bc2081f-9978-4df6-89bf-0e839857bf6f)

### Steps To Reproduce

Opening Telescope with carbonfox theme applied.

### Expected Behavior

Telescope prompt is not highlighted, and is the same color as Telescope's background.

**Comment by EdenEast** [comment]
Is that your cursorline? Does setting `:set nocursorline` give you a different result?

**Comment by arthurx07** [comment]
Ok, thank you. So that was the issue, didn't think that it could be the cursorline.
