### ISSUE TITLE
bug: vim: nightfox/lib/vim/compiler.lua:22: nesting of [[...]] is deprecated

### ISSUE THREAD

**Issue by jgb** [EdenEast/nightfox.nvim#372]
### Neovim version (nvim -v)

vim 9.0.1894

### Operating system/version

debian testing/unstable

### Describe the bug

Nightfox no longer works on vim/gvim since it got upgraded on debian to vim 9.0.1894.
It worked before that on an older version of vim.

From the debian/vim changelog, this is probably the culprit:

  * Build against Lua 5.1 instead of Lua 5.2 (Closes: #1050637)

The error I'm getting is as follows:

Error detected while processing nightfox.vim:

nightfox/lib/vim/compiler.lua:22: nesting of [[...]] is deprecated

### Steps To Reproduce

1) Try to use nightfox on the latest vim/gvim on debian

### Expected Behavior

Nightfox used to work on the previous vim release (compiled with lua 5.2) but the newer version is compiled with lua 5.1 and there nightfox no longer works.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "EdenEast/nightfox.nvim",
    config = function()
      require("nightfox").setup({
        -- setup here ...
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("nightfox")
```

**Comment by EdenEast** [comment]
This looks related to #370. I will add the  nested `[[` fix.
