### ISSUE TITLE
help: cannot change tthe color and style of MatchParen group

### ISSUE THREAD

**Issue by halshar** [EdenEast/nightfox.nvim#380]
### Neovim version (nvim -v)

v0.9.2

### Operating system/version

Fedora Linux - 38

### Describe the bug

I'm trying to change the MatchParen color for the carbonfox them but i'm not seeing any changes

```lua
return {
"EdenEast/nightfox.nvim",
lazy = false,
priority = 1000,
config = function()
require("nightfox").setup({
  options = {
    groups = {
      carbonfox = {
        MatchParen = { fg = "yellow" },
      },
    },
  },
})
vim.cmd("colorscheme carbonfox")
end,
}

```

### Steps To Reproduce

1. copy the config
2. go over any parenthesis

### Expected Behavior

![carbonfox](https://github.com/EdenEast/nightfox.nvim/assets/45795416/20772dfe-251b-4dd4-afdd-da65b8913a96)

what I want is for the opening and closing parenthesis to have the same block and color, in the above config I was trying with yellow but I don't see any changes

**Comment by halshar** [comment]
thank you, it works but how do I make both the highlight be a block of same color i.e purple color of the carbonfox theme?

**Comment by EdenEast** [comment]
Not sure I understand the question. Which highlight groups are you referring to? Or do you mean inverting the highlight group so the background is magenta and the foreground is the background?

**Comment by halshar** [comment]
![carbonfox](https://github.com/EdenEast/nightfox.nvim/assets/45795416/f3009305-4124-4ba0-a54f-3b95955c2232)

in the above screenshot only the opening parenthesis is highlighted with block, I want the same thing for the closing parenthesis as well, can this be done?

**Comment by EdenEast** [comment]
Your cursor is handed by your terminal and not neovim. I am guessing that you are using alacritty and have it set to reverse the current cell.

For example I am using wezterm and the cursor is static (always black foreground and white background).

![image](https://github.com/EdenEast/nightfox.nvim/assets/2746374/bb774250-7a70-4868-93de-f70c6f66e7a4)
![image](https://github.com/EdenEast/nightfox.nvim/assets/2746374/816dd508-b07e-4150-abb6-2ccd40be0c41)

**Comment by halshar** [comment]
no, what I mean is I want the opening and the closing parenthesis to be have cursor blocks



1. ![correct](https://github.com/EdenEast/nightfox.nvim/assets/45795416/36728601-5560-4b90-986e-705234ee6f21)
here, both the opening and closing parenthesis have cursor blocks

-----

2. ![wrong](https://github.com/EdenEast/nightfox.nvim/assets/45795416/b0b74adc-1f7e-4a5b-a104-464707bf1777)
and here, both the parenthesis are highlighted but only the opening one has cursor block

the first screenshot is of the default theme and the second is of carbonfox

**Comment by EdenEast** [comment]
The 'cursor block' you are referring to it just setting the background color (the default is: `MatchParen MatchParen    xxx ctermbg=6 guibg=DarkCyan`). 


## Option 1

Set the foreground and background of the `MatchParen` highlight group.

```lua
require("nightfox").setup({
  groups = {
    all = {
      MatchParen = { bg = "palette.yellow", fg = "bg1" },
    },
  },
})
```

## Option 2

Use the `reverse` style for `MatchParen` which reverses the foreground and background (see `:h attr-list` for list of styles)

```lua
require("nightfox").setup({
  groups = {
    all = {
      MatchParen = { fg = "palette.cyan", style = "reverse" },
    },
  },
})
```

## Option 3

Use builtin shortcut in nightfox for reverse the match parens with `options.inverse.match_paren = true`.

```lua
require("nightfox").setup({
  options = {
    inverse = {
      match_paren = true,
    },
  },
  groups = {
    all = {
      MatchParen = { fg = "palette.cyan" },
    },
  },
})
```

### Note

For the `groups` table it uses the `spec` table. If you want to refer to a palette color, prefix with `palette.`.

**Comment by EdenEast** [comment]
Neovim can only set the highlight for the matched pairs. As pairs are highlighted based on your cursor's position it requires one of the pairs to be behind your cursor. Neovim does not control the cursor that is handled by your terminal. That is something you would have to consult your terminals cursor settings.

**Comment by halshar** [comment]
![carbox-issue-02](https://github.com/EdenEast/nightfox.nvim/assets/45795416/835bc40b-f015-480f-b1ed-72cd84b6045c)

maybe I'm explaining something wrong, but this behavior works fine with default neovim theme along with the several other themes I have used in the past

**Comment by EdenEast** [comment]
Yes from the image that you provided your cursor is reversing the cell. I am guessing that you are using alacritty, (as that is the default behaviour). They both look like blocks because they are both different colors then the background color.
The default highlight only sets the background color and does not set a foreground color.

For example setting MatchParen to

```lua
MatchParen = { fg = "", bg = "palette.cyan" },
```

Would result in the following in alacritty:

![image](https://github.com/EdenEast/nightfox.nvim/assets/2746374/3055f67c-f448-41b6-be4d-f25555979046)

And the same line with a different foreground color (commented)

![image](https://github.com/EdenEast/nightfox.nvim/assets/2746374/1a3557fe-8251-48e2-944b-19e444a84d77)

And the same as the above but in wezterm

![image](https://github.com/EdenEast/nightfox.nvim/assets/2746374/85b52731-f6dc-4c3c-be7e-cce24d904800)

**Comment by halshar** [comment]
thanks a lot, this works and sorry for all the trouble :)
