### ISSUE TITLE
bug: Dayfox and Dawnfox colors are nothing like in screenshots

### ISSUE THREAD

**Issue by herrbischoff** [EdenEast/nightfox.nvim#389]
### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

macOS 14.1.2

### Describe the bug

After installing, the colors are not at all like shown in the screenshots. Check with and without tmux, in iTerm 2, Alacritty and Kitty and with a minimal config. Also, the iTerm 2 color scheme doesn't appear to reflect the refactored values yet. Lualine's colors are completely off.

Dayfox:

<img width="1172" alt="Screenshot 2023-12-16 at 22 22 09" src="https://github.com/EdenEast/nightfox.nvim/assets/8957346/6a37f6b1-cdf5-4171-a21b-72a199bb2c73">

Dawnfox:

<img width="1172" alt="Screenshot 2023-12-16 at 22 22 28" src="https://github.com/EdenEast/nightfox.nvim/assets/8957346/fb8711eb-7f30-4023-8f18-c1dd4dee9544">

### Steps To Reproduce

1. Install nightfox via Lazy.nvim.
2. Enable colorscheme

### Expected Behavior

Colors like the screenshots.

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "EdenEast/nightfox.nvim",
    lazy = false,
    priority = 1000,
  },

  {
    'nvim-lualine/lualine.nvim',
    config = function ()
      require('lualine').setup()
    end,
  },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("dayfox")
```

**Comment by EdenEast** [comment]
I am not I understand the issue you are having. From the screenshots you have provided everything looks correct. From what I see you have opened the start of the help with the default vim syntax highlights (not treesitter). As for the status bar that does look like lualine.

A note about the statusline in the screenshots that is not lualine but was my custom [feline] statusbar (see the note below the list of screenshots)

[feline]: https://github.com/EdenEast/nightfox.nvim/blob/main/misc/feline.lua

**Comment by herrbischoff** [comment]
Regarding the status bar, I seem to have missed that. But given that Lualine is listed as supported and the screenshots containing a very differently colored statusline, it's easy to get confused. If nothing else, that's my issue. The colors for Lualine look entirely out-of-place.

If the colors are as intended, feel free to close this issue.

**Comment by EdenEast** [comment]
When it says is supported that means that this colorscheme defines the file `lua/lualine/themes/<name>.lua` where name is the current applied colorscheme found by the variable `vim.g.colors_name`. If these files were not found then it would just use links to other highlight groups.

There are multiple status lines as lightline is also supported.
