### ISSUE TITLE
Base16 support has already been developed and you just have to merge it

### ISSUE THREAD

**Issue by arindamukawlas** [EdenEast/nightfox.nvim#394]
### Is your feature request related to a problem? Please describe.

@pardom has already developed support for base16 in https://github.com/EdenEast/nightfox.nvim/pull/354

### Describe the solution you'd like

Make any edits you want and then merge it. The pull request has been waiting for 7 months, why?

**Comment by EdenEast** [comment]
> Make any edits you want and then merge it. The pull request has been waiting for 7 months, why?

I am not sure you understand what it means to be a maintainer of an open source project. This is something I initially wrote for myself, then shared it for others if they liked it. The `why` is that life changes (health, jobs, family obligations) and what someone spends their free time on will also change.

From your profile it looks like you are new to the space of open source. In the future please keep in mind these things and be careful when asking `why` something has not been done in someone's own project.
