### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by vanguard-bit** [EdenEast/nightfox.nvim#403]
I am relatively new to nvim and I have no idea how to setup the UI(i somehow figured out other plugins).....
I really liked the the style in readme so I would request some sort of guide in setting the config like that.....

**Comment by arpangreat** [comment]
See typecraft youtube tutorials it will help you also you can search it on google , there're so many relevant blogs and tutorials.

**Comment by EdenEast** [comment]
Some video resources:
- [Understanding lua with neovim conf 2022 talk](https://www.youtube.com/watch?v=gjIl5Sfh2QQ)
- [Typecraft](https://www.youtube.com/playlist?list=PLsz00TDipIffreIaUNk64KxTIkQaGguqn)
- [Vhyrro Understanding Neovim
](https://www.youtube.com/@vhyrro)](https://www.youtube.com/playlist?list=PLx2ksyallYzW4WNYHD9xOFrPRYGlntAft)
- [Devaslife full neovim setup](https://www.youtube.com/watch?v=fFHlfbKVi30)

I would recommend using [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) as a good starting point for your config.

As for the screenshots see the note section in the readme for what is used:

<img width="432" alt="image" src="https://github.com/EdenEast/nightfox.nvim/assets/2746374/f49306d6-e13b-409c-93c9-df2be9dbfa0a">

That has links to the actual tabby and feline files that I was using. These were all custom and I have them linked in nightfox.
