### ISSUE TITLE
bug: wezterm has dayfox theme from this repo missing

### ISSUE THREAD

**Issue by skoch13** [EdenEast/nightfox.nvim#425]
### Neovim version (nvim -v)

v0.10.0-dev-2465+ga7788c2e2

### Operating system/version

MacOS 14.4

### Describe the bug

WezTerm doesn't have the `dayfox` theme provided by the extras

### Steps To Reproduce

1. Proceed to https://wezfurlong.org/wezterm/colorschemes/d/index.html#dayfox
2. Search for proper `dayfox`
3. cry 😢 

### Expected Behavior

I added the `dayfox theme locally, but I'd be much more convenient to have the proper one shipped with wezterm

**Comment by EdenEast** [comment]
It looks like wezterm is getting the colors from iterm2-color-schemes repo. These colors are coming from a PR that I made to the repo in [427](https://github.com/mbadolato/iTerm2-Color-Schemes/pull/427). This is correct and is still the same as this project.

**Comment by skoch13** [comment]
Thank you for your reply. If you search for say ‘dawnfox’ this repo will be mentioned, while for ‘dayfox’ it looks like themes collided with iterm2. That being said, ‘dayfox’ iterm2 theme lack tab bar colors for Wezterm, that’s why I raised this issue in the first place.

**Comment by skoch13** [comment]
@EdenEast could you please double-check this?
