### ISSUE TITLE
feature: border line colour

### ISSUE THREAD

**Issue by karshPrime** [EdenEast/nightfox.nvim#437]
### Is your feature request related to a problem? Please describe.

been just looking for ways to set custom colourcode for border line, aka the line that divides different vim panes. traditionally I would do something like-
```
vim.cmd('highlight VertSplit guifg=#808080 guibg=NONE ctermfg=160 ctermbg=NONE')
```
but something from within this theme (carbon fox to be exact) seems to overwrite that black/transparent.
I must mention I have set `transparent = true,` believing it only makes background transparent, though now I’m uncertain.

### Describe the solution you'd like

Either an explicit setting within config to set a colour value or support for vim highlight colour command. It is very likely that there's already some config for this within the theme, though I couldn't find that in the readme.

### Describe alternatives you've considered

nothing really, perhaps get used to it or switch themes.

### Additional context

Here's my custom config-
```
require('nightfox').setup({
    options = {
        transparent = true,
        colorblind = {
            enable = true,
            simulate_only = false,
            severity = { deutan = 1, },
        },
    },
})
vim.cmd("colorscheme carbonfox")
```

**Comment by EdenEast** [comment]
Nightfox would not be able to know that you have manually set `VertSplit` manually. You can define how nightfox will define highlight groups like `VertSplit`.

You can define this in the nightfox's setup.

```lua
require("nightfox").setup({
        groups = { -- Override how nightfox defines highlight groups
          all = { -- Which color palettes to apply
            -- The value can be either a color defined by:
            -- - '#RRGGBB' format
            -- palette.<value> to refer to the colorscheme's palette
            -- spec.<value> to refer to the colorscheme's spec
            VertSplit = { fg = "palette.comment", bg = "NONE" },

            -- Can also link to another highlight group
            Float = { link = "Number" },
          },
        },
      })
```

See [palette](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#palette) and [spec](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#spec) usage doc for more information.

**Comment by thatlittleboy** [comment]
@EdenEast 

I can't seem to get the snippet you mentioned working, here's a `repro.lua` trying to set the border colour to be `#7A49A5` ([purplish color](https://www.google.com/search?q=%237A49A5))

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "EdenEast/nightfox.nvim",
        config = function()
          require("nightfox").setup({
            groups = {
              all = {
                VertSplit = { fg = "#7A49A5", bg = "NONE" },
              },
            },
          })
        end,
    build = function()
      require("nightfox").compile()
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("nightfox")
```

But it is still gray after restarting, and running `nvim -u repro.lua repro.lua`

![image](https://github.com/user-attachments/assets/c349bfea-23cc-4336-87c4-8fb1886dc6ec)

**Comment by EdenEast** [comment]
Ah I think the highlight group you are looking for is `WinSeperator`

```
							*hl-WinSeparator*
WinSeparator	Separators between window splits.
```

`VertSplit` has been deprecated

```
- *hl-VertSplit*	Use |hl-WinSeparator| instead.
```
