### ISSUE TITLE
Popups in neotree have illegible headings

### ISSUE THREAD

**Issue by notahat** [EdenEast/nightfox.nvim#440]
### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

MacOS 14.5 (23F79)

### Describe the bug

Headings on popups in Neotree are black-on-dark, but only after the second time you start neovim.

![Screenshot 2024-05-29 at 12 04 33 PM](https://github.com/EdenEast/nightfox.nvim/assets/3866/979d7ecf-dc0e-4590-802f-118a5683e655)

### Steps To Reproduce

1. Start neovim, and let Lazy install everything
2. Open neo-tree with ":Neotree"
3. Select a file and hit "r" to rename

![Screenshot 2024-05-29 at 12 04 24 PM](https://github.com/EdenEast/nightfox.nvim/assets/3866/2a29786c-71ab-4263-9544-6cdcf91ca882)

4. Quit out of neovim with ":qa"
5. Start neovim again
6. Open neo-tree with ":Neotree"
7. Select a file and hit "r" to rename

![Screenshot 2024-05-29 at 12 04 33 PM](https://github.com/EdenEast/nightfox.nvim/assets/3866/979d7ecf-dc0e-4590-802f-118a5683e655)

### Expected Behavior

Neotree's popups should always display as they do at step 3 .

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    {
        "EdenEast/nightfox.nvim",
        config = function()
            require("nightfox").setup({})
        end,
    },
    {

        "nvim-neo-tree/neo-tree.nvim",
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-tree/nvim-web-devicons",
            "MunifTanjim/nui.nvim",
        },
        config = function()
            require("neo-tree").setup({})
        end,
    },
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("nightfox")
```

**Comment by notahat** [comment]
I went and had a look at the highlight groups, and the relevant one is `NeoTreeTitleBar`. Sure enough, on the first open of neovim it is:

```
NeoTreeTitleBar xxx guifg=#131a24 guibg=#71839b
```

and on the second open it is:

```
NeoTreeTitleBar xxx guifg=#14161b
```

**Comment by EdenEast** [comment]
This looks like an issue with Neotree as nightfox does not set or touch the highlight group `NeoTreeTitleBar`

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/206241e451c12f78969ff5ae53af45616ffc9b72/lua/neo-tree/ui/highlights.lua#L243

**Comment by EdenEast** [comment]
Looking further into this I was not able to reproduce this issue in my setup. I found that this is an issue with Neotree and plugin loading order.

Lazy loading Neotree seems to resolve the issue.

```lua
{
    "nvim-neo-tree/neo-tree.nvim",
    cmd = "Neotree",
    keys = {{
      "<leader>e",
      function() require("neo-tree.command").execute({ toggle = true, reveal = true }) end,
      desc = "Explorer NeoTree",
      remap = true,
    }},
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
    },
    config = function()
      require("neo-tree").setup({})
    end,
  }
  ```

An example of loading it on a key or a command.
