### ISSUE TITLE
feature: Float windows to be transparent aswell.

### ISSUE THREAD

**Issue by Redoxahmii** [EdenEast/nightfox.nvim#448]
### Is your feature request related to a problem? Please describe.

I can't seem to find this option in this unless i redefine complete palletes which doesn't look like a good way.

### Describe the solution you'd like

float windows like using telescope or using hover with `K` to have transparent when enabling transparent true.

### Describe alternatives you've considered

Create your own palette.

**Comment by B1kku** [comment]
> I can't seem to find this option in this unless i redefine complete palletes which doesn't look like a good way.

You can just set the bg of that group to NONE like this:
```lua
    require("nightfox").setup {
      groups = {
        all = {
          NormalFloat = { bg = "NONE" },
        }
      }
    }
```
There's some info on the README about this.

> float windows like using telescope or using hover with `K` to have transparent when enabling transparent true.

I agree, this should be a default when using `transparent = true`

**Comment by Redoxahmii** [comment]
Thanks for the info. it's standard for most colorschemes nowadays to have this as an option so hopefully they add this in future.
