### ISSUE TITLE
feature: Submit dawnfox, duskfox, nordfox and carbonfox to iTerm2-Color-Schemes

### ISSUE THREAD

**Issue by jacakira** [EdenEast/nightfox.nvim#460]
### Is your feature request related to a problem? Please describe.

Many terminals, such as Ghostty and Wezterm pull their themes from the following repo:
https://github.com/mbadolato/iTerm2-Color-Schemes/ 

There was a (resolved) issue back in May 2022, about adding the themes in this repo to iTerm2-Color-Schemes (https://github.com/EdenEast/nightfox.nvim/issues/156). However, the themes dawnfox, duskfox, nordfox and carbonfox, which presumably didn't exist at the time, are not in the iTerm2-Color-Schemes repo.

### Describe the solution you'd like

Add the latest version of all nightfox themes to https://github.com/mbadolato/iTerm2-Color-Schemes/ 

### Describe alternatives you've considered

It is possible to alternatively paste in the theme color-codes into terminal configs manually, but this is a less streamlined solution than having them available in https://github.com/mbadolato/iTerm2-Color-Schemes/.

**Comment by EdenEast** [comment]
I did port nightfox's themes to iTem2-Color-Schemes in this [PR](https://github.com/mbadolato/iTerm2-Color-Schemes/pull/427). 

When porting themes I only added `nightfox`, `dayfox` and `terafox` as these are the only **original** colorschemes from nightfox (made by me). The others come from other themes. In hindsight I would not have added them to nightfox but at the time I wanted to try those themes but use the colorscheme setup and structure that I made for nightfox. 

| name | original |
| ------ | -------- |
| Dawnfox | [Rose Pine Dawn](https://rosepinetheme.com/palette/) |
| Duskfox | [Rose Pine](https://rosepinetheme.com/palette/) |
| Carbonfox | [oxocarbon.nvim](https://github.com/nyoom-engineering/oxocarbon.nvim) |
| Nordfox | [Nord](https://www.nordtheme.com/) |

As I have not really made anything new if you want to use these colors in other ports like iTerm2-Color-Schemes I suggest that you use the original sources. I would like to separate original themes from community _foxes_ that come from other themes. That is something that I would like to do but dont have the time or priority now.
