### ISSUE TITLE
Could you share your Rust lang setup please?

### ISSUE THREAD

**Issue by cata0309** [EdenEast/nightfox.nvim#5]

**Comment by EdenEast** [comment]
You can find my configuration repo [here](https://github.com/EdenEast/nyx). My configuration is managed my [nix](https://nixos.org/). This lets me declaratively describe my machine or user's configuration. 

As for neovim and rust specifics, There are three major areas: Treesitter, Language server protocal (lsp) and Debug Adaptor Protocal (dap).

For treesitter you can find the plugins I use [here](https://github.com/EdenEast/nyx/blob/3c764ba/config/.config/nvim/lua/modules/lang/plugins.lua#L4-L12)
The configuration is [here](https://github.com/EdenEast/nyx/blob/3c764ba/config/.config/nvim/lua/modules/lang/treesitter.lua)

For lsp you can find the plugins I use [here](https://github.com/EdenEast/nyx/blob/3c764ba/config/.config/nvim/lua/modules/lsp/plugins.lua)
The configuration is in the same folder but the main file is [here](https://github.com/EdenEast/nyx/blob/3c764ba/config/.config/nvim/lua/modules/lsp/lspconfig.lua)

For dap you can find the plugins I use [here](https://github.com/EdenEast/nyx/blob/3c764ba/config/.config/nvim/lua/modules/editor/plugins.lua#L73-L81)
The configuration for rust specifics [here](https://github.com/EdenEast/nyx/blob/3c764ba/config/.config/nvim/lua/modules/editor/debug/rust.lua)

As for managing neovim, rustc, cargo, rust-analyzer and others I use nix to install and manage those.
(If you are interested, [neovim](https://github.com/EdenEast/nyx/blob/3c764ba/home/modules/shell/neovim.nix), and [rust](https://github.com/EdenEast/nyx/blob/3c764ba/home/modules/dev/rust.nix) nix files)
