### ISSUE TITLE
Colorscheme doesn't seem to be applying

### ISSUE THREAD

**Issue by devins2518** [EdenEast/nightfox.nvim#51]
[Can be seen here after doing `:colorscheme nightfox`.](https://0x0.st/-dy1.png).
The colorscheme does seem to affect the highlight values which is strange.
```
:highlight Normal
Normal         xxx guifg=#cdcecf guibg=#192330
```
My previous colorscheme was gruvbox which seems to be lingering even after deleting it.

**Comment by EdenEast** [comment]
If it works on your laptop I would check the difference between the two setups. Here are some of the things that I would check:

- Both machines have their plugins up to date with latest
- Check versions of the terminal you are using
- Check multiple terminals to see if one of them work
  - Other terminal examples: `alacritty`, `kitty`, `wezterm`

**Comment by devins2518** [comment]
I use nix so its actually the same setup :sweat_smile:. My laptop uses foot on wayland and it works fine. The issue is on my desktop which uses alacritty and interestingly enough, kitty and termite don't show this behavior. I'm struggling to find a reason as to why this is since alacritty doesn't have any caching afaik.

**Comment by EdenEast** [comment]
Ah another nix user! Reading though your config the only thing I see different between `dev` and `devin` is wayland. I see that you are overriding `alacritty` with `alacritty-ligatures` have tried to use the base alacritty pkg and see if the issue still persists. There might be an issue with the fork. I also use nix to configure my dotfiles if you are interested [nyx](https://github.com/edeneast/nyx).

**Comment by devins2518** [comment]
The issue still persists with the base alacritty package. I should note that I am using tmux but that didn't affect it on kitty

**Comment by EdenEast** [comment]
Ah yes that reminded me that I did have an issue recently with tmux and colorschemes with alacritty. I fixed it in this [commit](https://github.com/EdenEast/nyx/commit/ba62753abfcc24c909bb062c9c9141b98e6fab9f). The issue was that the `$TERM` variable was set to `alacritty` instead of something like `xterm-256color`. You can try that and it might fix your issue.

**Comment by devins2518** [comment]
Yeah, it seems tmux was messing up the colors. Adding `set-option -sa terminal-overrides ",alacritty*:Tc"` to my config fixed it! Thanks for all the help!
