### ISSUE TITLE
Add higlights for cmp menu

### ISSUE THREAD

**Issue by JoseConseco** [EdenEast/nightfox.nvim#56]
Ability to color cmp menu is its new feature. 
Implementation in [tokyo night](https://github.com/folke/tokyonight.nvim/commit/0d917649551662f8cd389c26460d70949630353d)

[Docs](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu)

**Comment by EdenEast** [comment]
Related to pr #55
