### ISSUE TITLE
Dim

### ISSUE THREAD

**Issue by SingularisArt** [EdenEast/nightfox.nvim#58]
Hello all.

How do I get rid of the inactive pane color?

Thanks

**Comment by EdenEast** [comment]
I think you have enabled the `alt_nc` option in your config. The default value for this is false so removing it from your setup will remove this. See the [configuration](https://github.com/EdenEast/nightfox.nvim#%EF%B8%8F-configuration) section for more information.

**Comment by SingularisArt** [comment]
Thanks!

**Comment by SingularisArt** [comment]
I added the line `alt_nc = true` to my config, but it didn't change anything.
Here's my config:

```lua
local nightfox = require('nightfox')

nightfox.setup({
  fox = 'duskfox',
  alt_nc = true,
  transparent = true,
  terminal_colors = true,
  styles = {
    comments = 'italic,bold',
    keywords = 'bold',
    functions = 'italic,bold'
  },
  colors = {
    bg_alt = "#000000",
  },
  inverse = {
    match_paren = true,
    visual = false,
    search = false
  },
})

nightfox.load()
```

**Comment by EdenEast** [comment]
In your setup function you have defined `alt_nc = true`. Remove that line from your setup function and it will disable that option. Please refer to the [configuration](https://github.com/EdenEast/nightfox.nvim#general) section of the readme for more information on the options and what they do.

**Comment by SingularisArt** [comment]
Thanks!
