### ISSUE TITLE
CSS – negative values not coloured correctly and selector coloring request

### ISSUE THREAD

**Issue by benfrain** [EdenEast/nightfox.nvim#59]
Thanks for the great theme!

I've noticed in CSS files, negative values don't get the same color as positive ones:

![image](https://user-images.githubusercontent.com/1318466/145049389-d6789a84-bc95-46ea-b543-97951bdbe4f5.png)

Not sure if that is intentional?

In addition, wondered if it might be preferable to have the selectors a different color; at present, selectors, properties and all non integer/function values get the same treatment. Unsure if this is a limitation of treesitter?

BTW – featured this theme here :) https://youtu.be/_evGrg4l3CY

**Comment by EdenEast** [comment]
From what I can tell this looks like a limitation of treesitter's highlight groups. I made sure to update my plugins and my css treesitter parser and was able to have negative numbers be recognized as numbers.
![image](https://user-images.githubusercontent.com/2746374/145057733-7881c36c-ffc2-4d55-9e8f-54f6d0e08037.png)

As for the color of the properties, it looks like treesitter does not define any unique  nodes for css that I can override. They are defined as just generic properties.
![image](https://user-images.githubusercontent.com/2746374/145058112-b68005e8-eef0-4c97-b2c7-9ab9bbbbe564.png)

(To view the highlight group defined by treesitter see the [playground](https://github.com/nvim-treesitter/playground#show-treesitter-and-syntax-highlight-groups-under-the-cursor))

When I disable highlighting for treesitter the normal vim syntax does define css specific syntax groups.
![image](https://user-images.githubusercontent.com/2746374/145058857-f0fc323b-43bf-4fd9-9b94-ad730bd7a8be.png)

*top:*
```
cssDefinition -> cssDefinition
cssPositioningProp -> StorageClass
```

(see [Syntax highlight groups](https://github.com/EdenEast/nightfox.nvim#syntax-highlight-groups) for more information)

---

In the future if the css parser make more differentiations I would like to revisit this.

If you would like to change the color of all `TSProperty` nodes for `css` you can prepend `css` to `TSProperty`. Example:

```lua
-- Set all `Property` nodes to red for css files
require("nightfox").setup({
  hlgroups = {
    cssTSProperty = { fg = "${red}" },
  },
})
```

Glad you are liking the theme!

**Comment by benfrain** [comment]
Thanks @EdenEast just reinstalled my css treesitter parser and all plugins up to date but I still don't get the negatives showing correctly. I'm on 0.6.0 currently. You?

I'll go and see if there is anything, issue wise, for improving the CSS on the Neovim treesitter repo and stick a link back here.

**Comment by EdenEast** [comment]
Interesting when change the filetype to `scss` I do have some more nodes to choose from.
![image](https://user-images.githubusercontent.com/2746374/145066951-18d4d578-4233-4bd8-a0c1-fc2295969cc4.png)

It still does recognize the negative number as a number though. I use nightly for my neovim version. But I also downgraded my version to 0.5.1 and still had the same result.

(If you are curious about my config you can find it here: [nyx](https://github.com/EdenEast/nyx/tree/main/config/.config/nvim))

**Comment by EdenEast** [comment]
Ohh looking at my config I noticed that I don't have the `scss` treesitter parser installed I just have the `css` one. When I installed the `scss` treesitter parser I have the same issue as you.
![image](https://user-images.githubusercontent.com/2746374/145068399-7c2a2ab8-4403-46bc-be4a-16589a6dbd4a.png)

**Comment by benfrain** [comment]
Iteresting. Looks like the scss parser is the integer issue for sure then.

**Comment by benfrain** [comment]
For reference, here are the issues on the scss parser repo:

https://github.com/serenadeai/tree-sitter-scss/issues/9
https://github.com/serenadeai/tree-sitter-scss/issues/8
