### ISSUE TITLE
Terminal colors?

### ISSUE THREAD

**Issue by FunctionalHacker** [EdenEast/nightfox.nvim#6]
It would be nice to have the same colors in my terminal. Is it possible you could f.ex supply something I can import into [terminal.sexy](https://terminal.sexy) so I can convert it to my terminal of choice?

**Comment by EdenEast** [comment]
Yes this is something on my todo list. Adding something like [tokyonight.nvim](https://github.com/folke/tokyonight.nvim#-extras) does with extras.  I just have not gotten to that. For now If you would like to see the colors they are defined in `lua/nightfox/colors/___fox.lua`.

**Comment by FunctionalHacker** [comment]
Here are the nightfox color in termite format

```
foreground = #CDCECF
background = #192330
color0     = #393B44
color1     = #C94F6D
color2     = #81B29A
color3     = #DBC074
color4     = #719CD6
color5     = #9D79D6
color6     = #63CDCF
color7     = #DFDFE0
color8     = #7F8C98
color9     = #D6616B
color10    = #58CD8B
color11    = #FFE37E
color12    = #84CEE4
color13    = #B8A1E3
color14    = #59F0FF
color15    = #F2F2F2
```
