### ISSUE TITLE
Color theme not supported  in Terminal (default Mac terminal)

### ISSUE THREAD

**Issue by yogeshelke** [EdenEast/nightfox.nvim#65]
Hi 
Thanks for fantastic color theme , it workes perfectly on iTerm2.
However when I switch to Terminal (default Mac terminal). Entire window is masked with Green color.
Is there any setting I´m missing?
Kindly help

![Nightfor-Nordfox-Mac-Terminal](https://user-images.githubusercontent.com/72194637/148700970-369fd02d-b3a0-4149-9dac-66d39a62f60b.png)

Thanks

**Comment by EdenEast** [comment]
The default `terminal.app` does not support true color. This is why it works in Iterm2. See the [requirements](https://github.com/edeneast/nightfox.nvim#%EF%B8%8F-requirements) section of the readme.
