### ISSUE TITLE
getting markdownH3 and H4 to have a color? Also italic not working.

### ISSUE THREAD

**Issue by michael-odonovan** [EdenEast/nightfox.nvim#67]
Thanks so much for your work on this plugin, it is amazing.
I am trying to get comments to be italic and different colors for markdownH3 H4 headings:
```
"vimscript
lua << EOF

local nightfox = require('nightfox')

nightfox.setup({
  styles = {
    comments = "italic", -- change style of comments to be italic
  },
  colors = {
    bg = "#111111",
		bg_highlight = "#333333"
  },
  hlgroups = {
    Folded = { fg = "c.blue", bg = "c.bg" }, -- line used for closed folds
    markdownH3 = { fg = "c.red", style = "bold" },
    markdownH4 = { fg = "c.green", style = "bold" },
  }
})

nightfox.load()

EOF
```
The other color changes are sticking but not the italics or markdown headings. Any ideas? I tried in the plugin itself and couldn't seem to get them to work there either.
thanks

**Comment by EdenEast** [comment]
Are you using `treesitter` for your highlighting? If you are then it does not differentiate between different Heading levels. For example:

![image](https://user-images.githubusercontent.com/2746374/151205635-f03abd8a-8d4c-40f3-8926-9c75b24d7e45.png)

If you are not then you are using the default vim `syntax` highlight groups. Here is where you can customize the colors. Here is an example of what highlight groups are defined.

![image](https://user-images.githubusercontent.com/2746374/151206305-e4a80780-5091-43cd-8542-4eac84394543.png)

If you would like to see the highlight groups defined for a specific item you can check out the [treesitter](https://github.com/EdenEast/nightfox.nvim#treesitter) section of the readme where it explains that treesitter [playground](https://github.com/nvim-treesitter/playground#show-treesitter-and-syntax-highlight-groups-under-the-cursor) comes with the command `:TSHighlightCapturesUnderCursor ` 

So for your hlgroups it would look something like: 

```lua
nightfox.setup({
  hlgroups = {
    -- Highlight groups are case sensitive
    htmlH3 = { fg = "${red}", style = "bold" },
    htmlH4 = { fg = "${green}", style = "bold" },
  }
})
```
> NOTE: For hlgroups to use the colors defined in the theme use the format ${color_name}

As for the comments not being italic I am not sure on that. If you resolve the other issues does it still happen? Also what terminal are you using?

**Comment by michael-odonovan** [comment]
Thanks for getting back, I didn't have any time to to look at this till today.
I have not yet moved to treesitter (am in process of changing over to init.lua) but have put in the htmlH3 .... that you suggested and it works great.
Comments still don't work but I am not too fused about them.
How do I get the pop up boxes with the info showing that you have going on? Is that a plugin?
I am using Alacritty terminal.
thanks again

**Comment by EdenEast** [comment]
The popup comes from the plugin  [nvim-treesitter/playground](https://github.com/nvim-treesitter/playground) which comes with the command `:TSHighlightCapturesUnderCursor`. This command will display the syntax highlighting groups being applied. This would be treesitter if highlighting is enabled or the default vim highlighting if not.

As for comments make sure that the font allacritty is using supports italic fonts. Checking your alacritty config file in your dotfiles I dont see that Italics fonts are defined.

See my alacritty config as an [example](https://github.com/EdenEast/nyx/blob/main/config/.config/alacritty/visual/font.yml)

**Comment by ecogest** [comment]
Also, regarding the italic part:
If you had compiled your configuration before, make sure you recompile it so that your new setup is taken into account.
```lua
lua require'nightfox'.compile()
```

**Comment by EdenEast** [comment]
This issue was open before the rewrite. Do you still have an issue after the rewrite.  For comments have you set comments to italics?. Here is a full example

```lua
require("nightfox").setup({
  options = {
    styles = {
      comments = "italic",
    },
  },
  groups = {
    htmlH3 = { fg = "pallet.red", style = "bold" },
    htmlH4 = { fg = "pallet.green", style = "bold" },
  }
})
```

Also as mentioned before if you are making changes make sure to clean any compiled files so the changes are actually applied.

**Comment by michael-odonovan** [comment]
`local status_ok, nightfox = pcall(require, "nightfox")
if not status_ok then
	return
end

nightfox.setup({
	options = {
		styles = {
			comments = "italic", -- change style of comments to be italic
		},
	},
	pallets = {
		bg = "#111111",
		bg_highlight = "#333333",
	},
	groups = {
		Folded = { fg = "c.blue", bg = "c.bg" }, -- color of highlight used for closed folds

		-- Note: Markdown headings are now controlled by vimwiki settings!
	},
})

vim.cmd("colorscheme nightfox")
`

**Comment by michael-odonovan** [comment]
I had a look at this https://github.com/EdenEast/nightfox.nvim#pallets but not really sure what I need to adjust in my pallets/bg. Is "bg" split into three values now?

**Comment by EdenEast** [comment]
Pallet overrides are defined per style. As for migrating between version 1 and version 2 in the [notice] section there is a migration table that can be expanded.

[notice]: https://github.com/EdenEast/nightfox.nvim/blob/main/readme.md#changes

| V1 color     | V2 pallet |
| ------------ | --------- |
| bg           | bg1       |
| bg_alt       | bg0       |
| bg_sidebar   | bg0       |
| bg_float     | bg0       |
| bg_popup     | bg0       |
| bg_highlight | bg3       |
| bg_visual    | sel0      |
| bg_search    | sel1      |
| fg           | fg1       |
| fg_alt       | fg2       |
| fg_gutter    | fg3       |

From the example above it would look like this:

```lua
local status_ok, nightfox = pcall(require, "nightfox")
if not status_ok then
  return
end

nightfox.setup({
  options = {
    styles = {
      comments = "italic",
    },
  },
  pallets = {
    nightfox = {
      bg1 = "#111111",
      bg3 = "#333333",
    },
  },
  groups = {
    Folded = { fg = "pallet.blue", bg = "bg1" },
  },
})

vim.cmd("colorscheme nightfox")
```

**Comment by michael-odonovan** [comment]
Thanks I got it all converted.
italic comments still elude me but I think it might be something to do with my system or Alacritty setup.
Really appreciate your help.
