### ISSUE TITLE
Feature Request: VSCode theme

### ISSUE THREAD

**Issue by bdwiel** [EdenEast/nightfox.nvim#68]
Just requesting that this theme (nightfox particularly) be converted to a VSCode theme.

**Comment by EdenEast** [comment]
I do not sure VSCode.  Anyone is welcome to port this theme to VSCode. This would require to also register the plugin to the store which is something that I am not personally interested in maintaining.

**Comment by EdenEast** [comment]
Thanks for letting me know about this port. Great to see someone ported the theme to vscode. I might add a link to it in the readme.

**Comment by RainbowShatter** [comment]
it got removed
