### ISSUE TITLE
Transparent background still activate after disabling

### ISSUE THREAD

**Issue by raven2cz** [EdenEast/nightfox.nvim#70]
I'm using **nordfox**. I'm using kitty with transparency, but I want to neovim without transparent background.

I configure fox this way:
```lua
local nightfox = require("nightfox")
nightfox.setup({
  transparent = false
})
nightfox.load()
```
But the nordfox has still transparent bg.

**Comment by r3gor** [comment]
the config is incorrect, try this:

```lua
nightfox.setup({
  options = {
    transparent = true,
  },
})
```
