### ISSUE TITLE
Highlighted text when substituting is too dark

### ISSUE THREAD

**Issue by eggbean** [EdenEast/nightfox.nvim#73]
Great theme. I'm using nordfox, but highlighting of matches when doing a substitution (`:%s/FOO/BAR/`) makes every instance of FOO black (or very dark grey) which makes it impossible to read on a dark background colour. I don't know if this is intentional or if it something in my config, but it makes it hard to see the matches as they could be whitespace. I would prefer the matches to be highlighted grey, like when searching.

What's the setting for this?

**Comment by EdenEast** [comment]
Here are two examples of what the default highlight should look like:

![bug-search-nordfox](https://user-images.githubusercontent.com/2746374/156790690-5dbfa8a4-4658-4ca8-981b-999ab976ef19.png)
![bug-sub-nordfox](https://user-images.githubusercontent.com/2746374/156790701-d264aafa-4345-47c0-9970-fb7afae411d2.png)

There are three highlight groups that deal with searching and substitution. These are:

- `Search`
- `IncSearch`
- `Substitute`

You can check the help for more information on these highlight groups. 

- `:help hl-Search`
- `:help hl-IncSearch`
- `:help hl-Substitute`

You can customize these hlgroups in nightfox's config.

```lua
require('nightfox').setup({
  hlgroups = {
    Search = { fg = "${fg}", bg = "${fg_gutter}" },
    IncSearch = { fg = "${bg}", bg = "${cyan}" },
    Substitute = { fg = "${bg}", bg = "${red}" },
  }
})
```

In this example I am setting the search background to be the same color as the line number.

If you have a specific color instead that you would like to use you can define it as well.

```lua
require('nightfox').setup({
  hlgroups = {
    Search = { fg = "${fg}", bg = "#123456" },
  }
})
```

**Comment by eggbean** [comment]
Thank you. I had to change it to a hex value, as red does not seem to be defined on my setup for some reason (the same happens if I put in nonsense colour name). Any idea what could be going on? Where are these colours defined?

**Comment by EdenEast** [comment]
Did you use the template format `${red}`? Also you can find the color definitions for all the colorscheme's [here](https://github.com/EdenEast/nightfox.nvim/tree/main/lua/nightfox/colors). Do you have an example of your config? or a `minimal_init.lua` file that I can reproduce your issues? Also seeing a screenshot might better help me understand your issue.

**Comment by eggbean** [comment]
My vim config is a spread over a lot of files and I've set it up so that most files are shared between vim, nvim, gvim and gvim for Windows, so it's difficult to show. The only lua part of the config is this theme in init.vim for nvim. Is there a way I can make a dumpfile or something?

But in any case it doesn't really matter now, as the problem has been fixed by me adding the same red colour hex code from the files you linked to, so they appear the same as in your screenshots. What I will do at some point is find the problem through the process of elimination by disabling plugins and parts of the config. You can close this issue, and I will post what I find if I found the problem in my config. Thanks.

**Comment by eggbean** [comment]
This is the order of all the files that are loaded from `:scriptnames`: https://termbin.com/2lhq, if that is any use.

**Comment by EdenEast** [comment]
Nightfox has recently been rewritten does your issue still persist after the rewrite?

**Comment by eggbean** [comment]
I have no updated the plugins, so I am still using the previous version. I deleted the `Substitute = { fg = "${bg}", bg = "#bf616a" },` line from my config, but then when I open the file again in vim and try a substitution it's red, as it should be.

So I am confused about why the colour is correct while I have deleted the line while not having updated the plugin.

**Comment by eggbean** [comment]
I spent some time trying to change the configuration for the update but I couldn't get it working, so I have held it back using the plugin manager until you make the documentation a bit less confusing for people like me who don't understand lua?

**Comment by eggbean** [comment]
I can't figure out what I am doing wrong. I have this at the end of my `init.vim` file: `lua require('config')` and in `./lua/config.lua` I have:

```
require('nightfox').setup({
  options = {
    compile_path = util.join_paths(vim.fn.stdpath("cache"), "nightfox"),
    compile_file_suffix = "_compiled", -- Compiled file suffix
    transparent = false,     -- Disable setting background
    terminal_colors = false, -- Set terminal colors (vim.g.terminal_color_*)
    dim_inactive = false,    -- Non focused panes set to alternative background
    styles = {               -- Style to be applied to different syntax groups
      comments = "italic",
      functions = "italic,bold",
      keywords = "bold",
      numbers = "NONE",
      strings = "NONE",
      types = "NONE",
      variables = "NONE",
    },
    inverse = {             -- Inverse highlight for different types
      match_paren = false,
      visual = false,
      search = false,
    },
    modules = {             -- List of various plugins and additional options
      -- ...
    },
  }
})

vim.cmd("colorscheme nightfox")
require('lualine').setup()
```
But on startup I get this error:

```
Error detected while processing /home/jason/.dotfiles/config/.config/nvim/init.vim:
line   27:
E5108: Error executing lua /home/jason/.dotfiles/config/.config/nvim/lua/config.lua:3: attempt to index global 'util' (a nil value)
stack traceback:
        /home/jason/.dotfiles/config/.config/nvim/lua/config.lua:3: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by EdenEast** [comment]
For config options you do not have to set any values if you are not changing them from the default. In the readme it looks like when I copied the defaults section I left in my util function that joins the paths for both windows and unix platforms. In the readme I will change that to make that more clear and so ppl dont call `util`.  Looking at the above example here this would be:

```lua
require("nightfox").setup({
  options = {
    terminal_colors = false, -- do not define colors for neovim's builtin terminal
    styles = {
      comments = "italic",
      functions = "italic,bold",
      keywords = "bold",
    },
  },
})

vim.cmd("colorscheme nightfox")
require('lualine').setup()
```

**Comment by eggbean** [comment]
Thanks, everything seems to be working fine, including the previous issue with the substitution highlighting.

I did know that defaults don't need to be included, but I added them so that it would be easier to make further changes to my config, at least until the time I am quite sure that it is how I want it to be. Cheers.

**Comment by eggbean** [comment]
One more thing - I use gitgutter and barbar plugins. Do I need to add them as modules in the configuration above, or do they get detected automatically? I don't understand the reason for the modules section in the configuration.

Currently I think the current tab highlight colour in barbar is too light when using nordfox.

**Comment by EdenEast** [comment]
Nightfox is built to be very configurable. Modules are used as a mechanizem for additional option per plugin or area (diagnostics, lsp, treesitter, etc...). Currently they are just booleans that say that they are enabled. If for some reason you do not want nightfox to define highlight groups for a certain plugin you could set the module to `false `. By default all nightfox's modules are enabled.

In the future I can see people wanting to add options for certain plugins and this is a way of implementing them. Currently they are mostly just booleans.

Also as a side note modules make contributing to nightfox easier as they are self contained examples of how a plugin is added.
