### ISSUE TITLE
Telescope styling alternative

### ISSUE THREAD

**Issue by haringsrob** [EdenEast/nightfox.nvim#74]
No need to add this, but I just wanted to share a quick setup that may help others.

You can style the prompt of telescope in your setup like this:

```lua
local nightfox = require('nightfox')
nightfox.setup({
    fox = 'nordfox',
    hlgroups = {
        TelescopeBorder = { fg = "${bg_popup}", bg = "${bg_popup}" },
        TelescopePromptBorder = { fg = "${bg_visual}", bg = "${bg_visual}" },
        TelescopePromptNormal = { fg = "${fg_sidebar}", bg = "${bg_visual}" },
        TelescopePromptPrefix = { fg = "${fg_sidebar}", bg = "${bg_visual}" },
        TelescopeNormal = { fg = "${fg_sidebar}", bg = "${bg_popup}" },
        TelescopePreviewTitle = { fg = "${bg_popup}", bg = "${green}" },
        TelescopePromptTitle = { fg = "${bg_popup}", bg = "${green}" },
        TelescopeResultsTitle = { fg = "${bg_popup}", bg = "${green}" },
        TelescopeMatching = { fg = "${error}", bg = "${NONE}" },
    }
})
nightfox.load()
```

<img width="1123" alt="Screenshot 2022-03-08 at 07 42 36" src="https://user-images.githubusercontent.com/866743/157181857-806f4d34-4b8e-4b83-b5a6-349b957a4a54.png">

<img width="1116" alt="Screenshot 2022-03-08 at 07 42 04" src="https://user-images.githubusercontent.com/866743/157181864-7f280e22-09cb-4c18-a3d9-0eefad09cdef.png">

It does not work on the fly if you change themes, but this setup works quite well with the 2 themes I use.

**Comment by sultanahamer** [comment]
If not the above, can we add some default in this plugin, At present when we fuzzy find, here is the output

﻿
![image](https://user-images.githubusercontent.com/11389059/161737706-509bfd4d-66ee-4a4b-96fc-2237758b4298.png)

The matching characters are really hard to find. If we check the last but one line 'kittty/navigator.conf' its really difficult to understand which of the characters are matching(blue on blue).

I am using duskfox and not sure if I have do something like nightfox compile etc to get better colors for Telescope

**Comment by EdenEast** [comment]
That looks like an issue with `duskfox` itself. It is using the same colors as `Search`. There should be more contrast for the search color for `duskfox`.

**Comment by sultanahamer** [comment]
@EdenEast thanks for the quick fix
