### ISSUE TITLE
Default theme darker after rewrite

### ISSUE THREAD

**Issue by maru-sama** [EdenEast/nightfox.nvim#82]
Hello,

Maybe this is a setting issue but after the rewrite some colors of the default theme are a lot darker than before, I especially noticed this when using telescope and checking the selection window, furthermore also some colors changed.
I am using treesitter for highlighting though so maybe this is related.

V1.0.0 Version which shows a nice border
![old](https://user-images.githubusercontent.com/152713/158579104-e6ed6831-4bbd-4820-9c89-6553163b246e.png)

Current Main, the border is barely visible.
![new](https://user-images.githubusercontent.com/152713/158579100-9b3d0a3e-13d2-49b4-a0f3-004165bc67b7.png)

My setup is as simple as using.
```
require("nightfox").setup({options = { transparent = true }})
vim.cmd([[ colorscheme nightfox ]])
```

I also see that the highlights are different, (I use treesitter as well).
V1.0.0
![oldhighlights](https://user-images.githubusercontent.com/152713/158580197-be1de1c3-e080-4c44-8aeb-5b2876fe3560.png)

Current
![newhighlights](https://user-images.githubusercontent.com/152713/158580202-2603901e-824c-4e11-a8d1-3a81579cba27.png)

**Comment by EdenEast** [comment]
Colors have been standardized for syntax

| color| syntax group|
| -----| -------------|
| red | builtins (variables and functions)|
| blue | functions|
| yellow | types|
| magenta | keywords|
| cyan | arguments and identifiers|
| green | strings|
| ornage | constants and numbers|
| pink | import and preprocs|


`require` in lua falls under `TSFuncBuiltin`. If you would like to change this there are two options.

1. Override `spec.syntax.builtin0` which is the spec for builtins. This would change the color for all builtins
1. Override the group `TSFuncBuiltin`.

```lua
-- Option 1
local specs = {
  nightfox = { -- name of the style
    syntax = {
      builtin0 = "cyan" -- Change `builtin0` to use the pallet color `cyan`
    }
  }
}

-- Option 2
local groups = {
  TSFuncBuiltin = { fg = "pallet.cyan" } -- Change the highlight group to use the pallet color cyan
}

require("nightfox").setup({ specs = specs, groups = groups })
```

Borders were also standardized as well. Telescope now using the same as all the other border groups (`bg4`). You
can override this to something lighter like `fg3` or what it was previously `pallet.blue`.

```lua
require('nightfox').setup({groups = {
  TelescopeBorder = { fg = "pallet.blue" },
}})
```

**Comment by maru-sama** [comment]
Thank you very much, this fixes the issue for me.

Last question, what group is this in?
![2dark](https://user-images.githubusercontent.com/152713/158760409-d8ae440b-bba3-4c92-920f-e0233a05d3a6.png)

As you can see the <Enter> is too dark now it used to be a lighter color previously

**Comment by EdenEast** [comment]
Those are `SpecialKey` which by default is linked to `NonText`.
