### ISSUE TITLE
Lualine README config

### ISSUE THREAD

**Issue by geralfonso** [EdenEast/nightfox.nvim#92]
Is there somewhere where I can find this specific Lualine config?

![Screenshot 2022-03-18 134908](https://user-images.githubusercontent.com/13323913/159065763-c4001cda-c62c-4720-bd9e-792a26268f26.png)

The one shown on README.
![Nightfox](https://user-images.githubusercontent.com/2746374/158456286-9e3ee657-60e6-49d8-b85e-dcab285b31c3.png)

**Comment by EdenEast** [comment]
That is not a lualine config but my own peronal [feline] config. You can find a link to my feline config [here][config]. My config also generates the colors automatically from the colorscheme applied. That is done [here][colors].

[feline]: https://github.com/feline-nvim/feline.nvim/
[config]: https://github.com/EdenEast/nyx/blob/1e370c/config/.config/nvim/lua/eden/modules/ui/feline/init.lua
[colors]: https://github.com/EdenEast/nyx/blob/1e370c/config/.config/nvim/lua/eden/modules/ui/colors.lua

**Comment by geralfonso** [comment]
It's so cool, im going to try it. Thanks for the answer!!!

**Comment by EdenEast** [comment]
@geralfonso  I was going to redo some of the utilities around my config's highlight colors (I have learned how to do it better after rewriting nightfox) I just pushed a [commit] if you are interested in checking out what changed.

[commit]: https://github.com/EdenEast/nyx/commit/573ff3f22da95c00ec71a094b3e1ec166c0afcdd

**Comment by geralfonso** [comment]
> @geralfonso I was going to redo some of the utilities around my config's highlight colors (I have learned how to do it better after rewriting nightfox) I just pushed a [commit](https://github.com/EdenEast/nyx/commit/573ff3f22da95c00ec71a094b3e1ec166c0afcdd) if you are interested in checking out what changed.

yeah sure. Thanks for the callout!
