### ISSUE TITLE
usage info: set darker background color for specified filetypes / buftypes

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [EdenEast/nightfox.nvim#93]
I wanted to know if there is functionality in this plugin to set a darker background to specified filetypes / buftypes. This would allow much easier configuration for backgrounds of say the quick fix lists and non-supported plugins like fugitive.

**Comment by ViRu-ThE-ViRuS** [comment]
j

**Comment by EdenEast** [comment]
Nightfox does not have a way to set the background color for a specific file/buffer type. This can be done though your config though with [:help winhighlight](https://neovim.io/doc/user/options.html#'winhighlight'). 

There are two ways of implementing this. 

1. In a your neovim's config directory using a `after/ftplugin/<ft>.lua` file (`:help ftplugin`)

```lua
-- after/ftplugin/gitcommit.lua
vim.cmd([[set winhighlight=Normal:NormalFloat]])
```

2. Create an autocmd 
```lua
local filetypes = { "qf", "fugitiveblame", "vista", "vista_kind" }
local cmd = string.format(
  "autocmd FileType %s setlocal winhighlight=Normal:NormalFloat,SignColumn:NormalFloat",
  table.concat(filetypes, ",")
)
vim.cmd(cmd)
```

**Comment by ViRu-ThE-ViRuS** [comment]
thanks, this works!!
