### ISSUE TITLE
How can I change the colour for dim_inactive?

### ISSUE THREAD

**Issue by eggbean** [EdenEast/nightfox.nvim#97]
I would like to change the colour for dim_inactive so that it is only slightly darker than the normal background colour. How do I do that?

**Comment by eggbean** [comment]
Also, I use `barbar.nvim` with `nordfox` and I was wondering if I need to do anything to get the tabline styled, or is it doing it automatically? The current tab colour seems a bit bright.

**Comment by EdenEast** [comment]
`dim_inactive` is a short hand for setting `NormalNC` highlight group (`:help hl-NormalNC`). It uses the `spec` value `bg0`

| Key     | Description                           |
| ------- | ------------------------------------- |
| bg0     | Darker bg (status line and float)     |
